#!/usr/bin/env python3
"""
Build the "Jämför ändring" paragraph list for one law from the official
Regeringskansliet "Fulltext" DOCX.

The DOCX keeps BOTH versions of every paragraph that is about to change
("/Upphör att gälla U:YYYY-MM-DD/" = old, "/Träder i kraft I:YYYY-MM-DD/" = new).
We parse the DOCX twice with build_laws_from_docx.parse():
  * once as of the day BEFORE the effective date  -> old wording
  * once as of the effective date                  -> new wording
and compare per section id:
  in both, text differs -> 'ändrad'
  only in new           -> 'ny'
  only in old           -> 'upphävd'

Usage:
  python3 build_amendments_from_docx.py --docx DOCX --effective 2026-07-01 \
      --export konkurslagAmendmentParagraphs --out OUT.ts
"""
import argparse, datetime, json, sys, os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_laws_from_docx as b


def reference(chapter, section, chaptered):
    suffix = f" {section['suffix']}" if section.get('suffix') else ''
    sec = f"{section['number']}{suffix} §"
    if not chaptered:
        return sec
    ch_suffix = chapter.get('suffix') or ''
    return f"{chapter['number']}{ch_suffix} kap. {sec}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--docx', required=True)
    ap.add_argument('--effective', required=True)
    ap.add_argument('--export', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    eff = datetime.date.fromisoformat(a.effective)
    before = (eff - datetime.timedelta(days=1)).isoformat()

    _, ch_old, chaptered, _, _ = b.parse(a.docx, before)
    _, ch_new, _, _, _ = b.parse(a.docx, a.effective)

    def index(chs):
        return {s['id']: (c, s) for c in chs for s in c['sections']}

    old, new = index(ch_old), index(ch_new)

    def sort_key(sid):
        c, s = (new.get(sid) or old.get(sid))
        return (c['number'], c.get('suffix') or '', s['number'], s.get('suffix') or '')

    paragraphs = []
    for sid in sorted(set(old) | set(new), key=sort_key):
        o, n = old.get(sid), new.get(sid)
        if o and n:
            if o[1]['text'] == n[1]['text']:
                continue
            kind, ot, nt, (c, s) = 'ändrad', o[1]['text'], n[1]['text'], n
        elif n:
            kind, ot, nt, (c, s) = 'ny', None, n[1]['text'], n
        else:
            kind, ot, nt, (c, s) = 'upphävd', o[1]['text'], None, o
        paragraphs.append({
            'id': sid,
            'reference': reference(c, s, chaptered),
            'changeType': kind,
            'oldText': ot,
            'newText': nt,
        })

    body = json.dumps(paragraphs, ensure_ascii=False, indent=2)
    header = (
        '// Generated by backend/build_amendments_from_docx.py from the official DOCX\n'
        f'// (Regeringskansliet fulltext). Old wording = version in force {before},\n'
        f'// new wording = version in force {a.effective}. Do not edit by hand - regenerate.\n\n'
        "import type { AmendmentParagraph } from './lawAmendments';\n\n"
    )
    open(a.out, 'w', encoding='utf-8').write(
        f'{header}export const {a.export}: AmendmentParagraph[] = {body};\n')
    kinds = {k: sum(1 for p in paragraphs if p['changeType'] == k) for k in ('ändrad', 'ny', 'upphävd')}
    print(a.export, len(paragraphs), kinds)


if __name__ == '__main__':
    main()
