// Generated by backend/build_amendments_from_docx.py from the official DOCX
// (Regeringskansliet fulltext). Old wording = version in force 2026-06-30,
// new wording = version in force 2026-07-01. Do not edit by hand - regenerate.

import type { AmendmentParagraph } from './lawAmendments';

export const aktiebolagslagAmendmentParagraphs: AmendmentParagraph[] = [
  {
    "id": "kap-25-§-51",
    "reference": "25 kap. 51 §",
    "changeType": "ändrad",
    "oldText": "Om en konkurs avslutas med överskott eller läggs ned efter frivillig uppgörelse eller om egendomen i konkursboet återställs till bolaget till följd av att ackord har fastställts, skall allmän domstol i samband med att konkursen avslutas besluta att bolaget skall gå i likvidation. Ett sådant beslut gäller omedelbart.\n\nVar bolaget i likvidation när det försattes i konkurs, skall likvidationen fortsätta enligt 44 §, om konkursen avslutas på det sätt som anges i första stycket.",
    "newText": "Om en konkurs avslutas med överskott eller läggs ner efter en frivillig uppgörelse, eller om egendomen i konkursboet återställs till bolaget till följd av att ett ackord har fastställts, ska allmän domstol i anslutning till att konkursen har avslutats besluta att bolaget ska gå i likvidation. Ett sådant beslut gäller omedelbart.\n\nOm bolaget var i likvidation när det försattes i konkurs ska likvidationen fortsätta enligt 44 §, om konkursen avslutas på det sätt som anges i första stycket. Lag (2025:804)."
  }
];
