// Lag (2022:964) om företagsrekonstruktion
// Generated by backend/build_laws_from_docx.py from the official DOCX (Regeringskansliet fulltext).
// Versions in force on 2026-10-07. Do not edit by hand - fix the parser or the source DOCX and regenerate.
// Last amended: SFS 2024:126

import { LegalText } from '../legalTexts';

export const företagsrekonstruktion: LegalText = {
  "id": "sfs-2022-964",
  "title": "Lag (2022:964) om företagsrekonstruktion",
  "sfsNumber": "2022:964",
  "department": "Justitiedepartementet L2",
  "issued": "2022-06-16",
  "lastAmended": "SFS 2024:126",
  "chaptered": true,
  "chapters": [
    {
      "id": "kap-1",
      "number": 1,
      "title": "Inledande bestämmelser",
      "sections": [
        {
          "id": "kap-1-§-1",
          "number": 1,
          "text": "Denna lag gäller för näringsidkare med ekonomiska svårigheter som, efter beslut av domstol, i ett särskilt förfarande kan rekonstruera sin verksamhet under ledning av en rekonstruktör (företagsrekonstruktion).",
          "references": [],
          "heading": "Lagens tillämpningsområde"
        },
        {
          "id": "kap-1-§-2",
          "number": 2,
          "text": "Lagen gäller inte för gäldenärer som är\n   1. kreditinstitut,\n   2. försäkringsföretag,\n   3. tjänstepensionsföretag,\n   4. värdepappersbolag,\n   5. centrala motparter eller clearingbolag,\n   6. värdepapperscentraler, eller\n   7. finansiella institut eller holdingföretag som är försatta i resolution enligt lagen (2015:1016) om resolution.\n\nLagen gäller inte heller för sådana gäldenärer där staten, en kommun, en region eller ett kommunalförbund har ett bestämmande inflytande i verksamheten. Lag (2024:126).",
          "references": []
        },
        {
          "id": "kap-1-§-3",
          "number": 3,
          "text": "Innehållet i lagen är uppdelat enligt följande.\n\n1 kap. - Inledande bestämmelser\n\n2 kap. - Företagsrekonstruktion i allmänhet\n\n3 kap. - Avtal som ingåtts före beslutet om företagsrekonstruktion\n\n4 kap. - Planförhandling under företagsrekonstruktionen\n\n5 kap. - Återvinning och kvittning under företagsrekonstruktionen\n\n6 kap. - Företagsrekonstruktionens upphörande\n\n7 kap. - Tillsyn över rekonstruktörer\n\n8 kap. - Straff och skadestånd",
          "references": [],
          "heading": "Lagens innehåll"
        },
        {
          "id": "kap-1-§-4",
          "number": 4,
          "text": "Bestämmelser i lagen (2015:860) om internationella säkerhetsrätter i lösa saker som avviker från denna lag gäller framför bestämmelserna i denna lag.",
          "references": [],
          "heading": "Internationella säkerhetsrätter",
          "groupHeading": "9 kap. - Övriga bestämmelser"
        }
      ]
    },
    {
      "id": "kap-2",
      "number": 2,
      "title": "Företagsrekonstruktion i allmänhet",
      "sections": [
        {
          "id": "kap-2-§-1",
          "number": 1,
          "text": "En ansökan om företagsrekonstruktion får göras av gäldenären eller av en borgenär. Ansökan görs skriftligen till tingsrätten.\n\nSökanden ska ange och styrka de omständigheter som gör rätten behörig, om de inte är kända.\n\nI 3 och 4 §§ lagen (2017:473) med kompletterande bestämmelser till 2015 års insolvensförordning finns ytterligare bestämmelser om ansökans innehåll.",
          "references": [
            "3 och 4 §§"
          ],
          "heading": "Ansökan om företagsrekonstruktion"
        },
        {
          "id": "kap-2-§-2",
          "number": 2,
          "text": "Regeringen kan med stöd av 8 kap. 7 § regeringsformen meddela föreskrifter om vilka tingsrätter som får pröva en ansökan om företagsrekonstruktion.",
          "references": [
            "8 kap. 7 §"
          ]
        },
        {
          "id": "kap-2-§-3",
          "number": 3,
          "text": "En ansökan om företagsrekonstruktion ska vara egenhändigt undertecknad av sökanden eller sökandens ombud.\n\nOm ansökan ges in elektroniskt, ska den skrivas under med en sådan avancerad elektronisk underskrift som avses i artikel 3 i Europaparlamentets och rådets förordning (EU) nr 910/2014 av den 23 juli 2014 om elektronisk identifiering och betrodda tjänster för elektroniska transaktioner på den inre marknaden och om upphävande av direktiv 1999/93/EG, i den ursprungliga lydelsen.",
          "references": []
        },
        {
          "id": "kap-2-§-4",
          "number": 4,
          "text": "En ansökan av gäldenären ska innehålla\n   1. en kortfattad redogörelse för gäldenärens ekonomi och orsakerna till de ekonomiska svårigheterna,\n   2. en borgenärsförteckning,\n   3. en redogörelse för hur gäldenären avser att verksamheten ska bedrivas i fortsättningen och hur verksamhetens livskraft ska säkerställas,\n   4. ett förslag till rekonstruktör och de uppgifter som behövs för att rätten ska kunna bedöma hans eller hennes lämplighet för uppdraget, och\n   5. uppgift om vilka borgenärer som har kontaktats före ansökan och deras inställning till förslaget till rekonstruktör.",
          "references": []
        },
        {
          "id": "kap-2-§-5",
          "number": 5,
          "text": "En ansökan av en borgenär ska innehålla\n   1. uppgift om borgenärens fordran på gäldenären,\n   2. upplysningar om gäldenärens ekonomiska svårigheter,\n   3. ett förslag till rekonstruktör och de uppgifter som behövs för att rätten ska kunna bedöma hans eller hennes lämplighet för uppdraget, och\n   4. uppgift om vilka andra borgenärer som har kontaktats före ansökan och deras inställning till förslaget till rekonstruktör.",
          "references": []
        },
        {
          "id": "kap-2-§-6",
          "number": 6,
          "text": "Om en ansökan inte uppfyller kraven i 1 och 3-5 §§ ska sökanden föreläggas att avhjälpa bristen. För det fall sökanden inte följer föreläggandet ska ansökan avvisas.",
          "references": [
            "1 och 3-5 §§"
          ]
        },
        {
          "id": "kap-2-§-7",
          "number": 7,
          "text": "Om gäldenärens ansökan inte avvisas, ska rätten genast pröva den.",
          "references": [],
          "heading": "Prövning av ansökan om företagsrekonstruktion"
        },
        {
          "id": "kap-2-§-8",
          "number": 8,
          "text": "Om en borgenärs ansökan inte avvisas, ska rätten inom två veckor från det att ansökan gjordes hålla ett sammanträde för prövning av ansökan. Om det finns särskilda skäl, får sammanträdet hållas senare, dock senast inom sex veckor.\n\nTill sammanträdet ska den borgenär som ansökt om företagsrekonstruktion och gäldenären kallas. Gäldenären ska i kallelsen föreläggas att senast vid sammanträdet yttra sig över ansökan. Kallelsen ska innehålla en upplysning om innehållet i 9 §.\n\nBorgenären och gäldenären ska delges kallelsen. Delgivning med gäldenären får inte ske enligt 34-38 och 48 §§ delgivningslagen (2010:1932).",
          "references": [
            "9 §",
            "34-38 och 48 §§"
          ]
        },
        {
          "id": "kap-2-§-9",
          "number": 9,
          "text": "En borgenärs ansökan förfaller om\n   1. gäldenären skriftligen bestrider ansökan,\n   2. gäldenären eller borgenären uteblir från det sammanträde som avses i 8 §, eller\n   3. gäldenären försätts i konkurs.",
          "references": [
            "8 §"
          ]
        },
        {
          "id": "kap-2-§-10",
          "number": 10,
          "text": "Företagsrekonstruktion får beslutas endast om\n   1. det kan antas att gäldenären inte kan betala sina förfallna skulder eller att en sådan oförmåga inträder inom kort eller att gäldenären i något annat avseende har ekonomiska svårigheter som innebär en risk för insolvens, och\n   2. det finns grundad anledning att anta att verksamhetens livskraft kan säkras genom rekonstruktionen.",
          "references": [],
          "heading": "Beslut om företagsrekonstruktion"
        },
        {
          "id": "kap-2-§-11",
          "number": 11,
          "text": "Företagsrekonstruktion får inte beslutas om gäldenärens bokföring har sådana brister eller fel att rörelsens förlopp, ekonomiska resultat eller ställning i huvudsak inte går att bedöma.",
          "references": []
        },
        {
          "id": "kap-2-§-12",
          "number": 12,
          "text": "En ansökan om företagsrekonstruktion som görs av en borgenär får bifallas endast om gäldenären har medgett ansökan.",
          "references": []
        },
        {
          "id": "kap-2-§-13",
          "number": 13,
          "text": "Om företagsrekonstruktion beslutas, ska rätten samtidigt utse en rekonstruktör. Finns det särskilda skäl får fler än en rekonstruktör utses. Innan rätten utser en rekonstruktör ska tillsynsmyndigheten ges tillfälle att yttra sig.\n\nRätten ska också bestämma tidpunkt för ett borgenärssammanträde inför rätten. Sammanträdet ska hållas inom tre veckor från beslutet om företagsrekonstruktion eller den längre tid efter beslutet som är nödvändig.",
          "references": []
        },
        {
          "id": "kap-2-§-14",
          "number": 14,
          "text": "Rekonstruktören ska inom en vecka från beslutet om företagsrekonstruktion underrätta samtliga kända borgenärer om beslutet.\n\nTill underrättelsen ska bifogas\n   1. en preliminär förteckning över gäldenärens tillgångar och skulder,\n   2. gäldenärens senaste årsredovisning eller årsbokslut och de ytterligare upplysningar som behövs om gäldenärens ekonomiska ställning,\n   3. uppgift om orsakerna till de ekonomiska svårigheterna och om hur verksamheten kan rekonstrueras, och\n   4. upplysning om den tidpunkt för borgenärssammanträde som bestämts enligt 13 § andra stycket.\n\nOm antalet borgenärer med fordringar utan förmånsrätt är mycket stort, får underrättelser till dessa borgenärer ersättas av ett tillkännagivande genom kungörelse. En sådan kungörelse ska innehålla upplysning om beslutet om företagsrekonstruktion och om tidpunkten för borgenärssammanträdet.",
          "references": [
            "13 §"
          ]
        },
        {
          "id": "kap-2-§-15",
          "number": 15,
          "text": "En rekonstruktör ska uppfylla de krav som framgår av 7 kap. 1 § första stycket konkurslagen (1987:672) och ha borgenärernas förtroende.\n\nVid bedömningen av om någon är lämplig som rekonstruktör ska det särskilt beaktas om han eller hon har erfarenhet av att i egenskap av konkursförvaltare fortsätta driva rörelse för ett konkursbos räkning enligt 8 kap. 2 § konkurslagen eller har annan motsvarande erfarenhet.",
          "references": [
            "7 kap. 1 §",
            "8 kap. 2 §"
          ],
          "heading": "Rekonstruktören"
        },
        {
          "id": "kap-2-§-16",
          "number": 16,
          "text": "Under företagsrekonstruktionen ska rekonstruktören undersöka om den verksamhet som gäldenären bedriver kan fortsätta helt eller delvis och i så fall på vilket sätt. Rekonstruktören ska dessutom biträda gäldenären med att upprätta en rekonstruktionsplan och i övrigt fullgöra de uppgifter som framgår av lagen.\n\nRekonstruktören ska verka för att borgenärernas intressen inte åsidosätts.\n\nRekonstruktören får anlita ett sakkunnigt biträde.",
          "references": []
        },
        {
          "id": "kap-2-§-17",
          "number": 17,
          "text": "En rekonstruktör som inte är lämplig eller av någon annan orsak bör skiljas från uppdraget ska entledigas av rätten. En fråga om entledigande tas upp på begäran av tillsynsmyndigheten, rekonstruktören, en borgenär eller gäldenären.\n\nTillsynsmyndigheten ska ges tillfälle att yttra sig innan rätten prövar en fråga om entledigande.",
          "references": []
        },
        {
          "id": "kap-2-§-18",
          "number": 18,
          "text": "Vid borgenärssammanträdet ska borgenärerna ges tillfälle att yttra sig i frågan om huruvida företagsrekonstruktionen bör fortsätta.\n\nOm någon borgenär begär det, ska rätten vid sammanträdet bland borgenärerna utse en borgenärskommitté. I kommittén får det ingå högst tre personer. Om gäldenären under det senast förflutna räkenskapsåret har sysselsatt i genomsnitt minst 25 arbetstagare, har de anställda rätt att därutöver utse en representant i kommittén. Om det finns särskilda skäl, får rätten utse ytterligare personer att ingå i borgenärskommittén.\n\nRekonstruktören ska ge borgenärskommittén tillfälle att yttra sig i väsentliga frågor, om inte något hindrar det.",
          "references": [],
          "heading": "Borgenärssammanträde och borgenärskommitté"
        },
        {
          "id": "kap-2-§-19",
          "number": 19,
          "text": "Gäldenären är skyldig att lämna alla upplysningar till rekonstruktören om sina ekonomiska förhållanden som är av betydelse för rekonstruktionen av verksamheten.\n\nGäldenären ska följa rekonstruktörens anvisningar om hur verksamheten ska bedrivas.",
          "references": [],
          "heading": "Gäldenärens skyldigheter"
        },
        {
          "id": "kap-2-§-20",
          "number": 20,
          "text": "Under företagsrekonstruktionen behåller gäldenären rådigheten över sin egendom. Utan rekonstruktörens samtycke får dock gäldenären inte\n   1. fullgöra förpliktelser som uppkommit före beslutet om företagsrekonstruktion eller ställa säkerhet för sådana förpliktelser,\n   2. åta sig nya förpliktelser som ligger utanför den löpande förvaltningen av verksamheten, eller\n   3. överlåta, pantsätta eller upplåta annan rätt till egendom av väsentlig betydelse för gäldenärens verksamhet.\n\nKrav på rekonstruktörens samtycke finns även i 3 kap. 2 och 9 §§.",
          "references": [
            "3 kap. 2 och 9 §§"
          ]
        },
        {
          "id": "kap-2-§-21",
          "number": 21,
          "text": "Rekonstruktören får samtycka till en åtgärd även i andra fall än de som anges i 20 §.\n\nRekonstruktören får samtycka till att gäldenären fullgör en förpliktelse enligt 20 § första stycket 1 endast om det finns synnerliga skäl.",
          "references": [
            "20 §"
          ]
        },
        {
          "id": "kap-2-§-22",
          "number": 22,
          "text": "En rättshandling som gäldenären företar i strid med 20 § första stycket 1-3 ska gå åter om rekonstruktören, inom skälig tid från det att han eller hon fick eller borde ha fått kännedom om rättshandlingen, begär det.\n\nEn rättshandling mellan gäldenären och någon annan som företas senast den dag då företagsrekonstruktionen registrerades i insolvensregistret ska gälla trots första stycket, om det inte visas att motparten kände till eller hade skälig anledning att anta att företagsrekonstruktion hade beslutats för gäldenären.",
          "references": [
            "20 §"
          ],
          "heading": "Återgång av en rättshandling"
        },
        {
          "id": "kap-2-§-23",
          "number": 23,
          "text": "Under den tid som företagsrekonstruktionen pågår får utmätning eller annan verkställighet enligt utsökningsbalken inte ske mot gäldenären. Under denna tid får en borgenär inte heller på annat sätt realisera gäldenärens tillgångar.\n\nVerkställighet eller realisation får dock ske för en fordran\n   1. som borgenären har handpanträtt eller retentionsrätt i, om det inte är sannolikt att företagsrekonstruktionen därigenom äventyras eller om borgenären annars skulle drabbas oskäligt hårt,\n   2. som avser underhållsbidrag, eller\n   3. på lön eller annan ersättning eller på pension som skulle ha haft förmånsrätt enligt 12 eller 13 § förmånsrättslagen (1970:979) eller på uppsägningslön, allt till den del fordran inte omfattas av den statliga lönegarantin enligt lönegarantilagen (1992:497).\n\nFör realisation enligt andra stycket 1 krävs rekonstruktörens samtycke. Om borgenären realiserar gäldenärens tillgångar i strid med kravet på samtycke gäller inte rättshandlingen.",
          "references": [
            "13 §"
          ],
          "heading": "Exekutiva åtgärder under en företagsrekonstruktion"
        },
        {
          "id": "kap-2-§-24",
          "number": 24,
          "text": "Under den tid som företagsrekonstruktionen pågår får handräckning enligt lagen (1978:599) om avbetalningsköp mellan näringsidkare m.fl. inte ske. Inte heller får beslut om kvarstad eller betalningssäkring meddelas.",
          "references": []
        },
        {
          "id": "kap-2-§-25",
          "number": 25,
          "text": "Om det finns särskilda skäl att befara att gäldenären vidtar eller låter bli att vidta en viss åtgärd och därigenom sätter en borgenärs rätt i fara, får rätten på borgenärens begäran besluta om en lämplig åtgärd för att säkerställa borgenärens rätt. Bestämmelserna i 23 § hindrar inte verkställighet av ett sådant beslut.",
          "references": [
            "23 §"
          ]
        },
        {
          "id": "kap-2-§-26",
          "number": 26,
          "text": "I 2 kap. 10 a § konkurslagen (1987:672) finns föreskrifter om en borgenärs ansökan om att gäldenären ska försättas i konkurs under en pågående företagsrekonstruktion.",
          "references": [
            "2 kap. 10 a §"
          ]
        }
      ]
    },
    {
      "id": "kap-3",
      "number": 3,
      "title": "Avtal som ingåtts före beslutet om företagsrekonstruktion",
      "sections": [
        {
          "id": "kap-3-§-1",
          "number": 1,
          "text": "När en ansökan om företagsrekonstruktion har gjorts, får en motpart i ett avtal med gäldenären inte häva avtalet på grund av ett dröjsmål med betalning eller någon annan prestation om dröjsmålet inträffat eller befarats inträffa före beslutet om företagsrekonstruktion. Detta gäller inte om något annat anges i detta kapitel.",
          "references": [],
          "heading": "Hinder mot hävning"
        },
        {
          "id": "kap-3-§-2",
          "number": 2,
          "text": "Gäldenären får med rekonstruktörens samtycke bestämma att ett avtal som ingåtts före beslutet om företagsrekonstruktion ska fullföljas. Rekonstruktörens samtycke krävs dock inte om avtalet ligger inom den löpande förvaltningen av verksamheten.\n\nOm avtalet gäller fortlöpande eller delbara prestationer får gäldenären bestämma att avtalet ska fullföljas endast för viss tid eller mängd av de prestationer som återstår att fullgöra. Det gäller dock inte om en sådan begränsning skulle medföra en betydande olägenhet för motparten eller om motpartens rätt till gäldenärens prestationer gäller mot gäldenärens borgenärer.",
          "references": [],
          "heading": "Gäldenärens rätt till fullföljd"
        },
        {
          "id": "kap-3-§-3",
          "number": 3,
          "text": "Om gäldenären bestämmer att ett avtal ska fullföljas enligt 2 § ska gäldenären och dennes motpart fullgöra de prestationer som återstår enligt den del av avtalet som ska fullföljas.\n\nI den utsträckning som gäldenärens prestationer enligt avtalet inte kan delas upp utan betydande olägenhet för motparten, ska gäldenären även fullgöra sådana prestationer som svarar mot prestationer som motparten har fullgjort före beslutet om företagsrekonstruktion.\n\nMotpartens krav enligt första och andra styckena ska anses ha uppkommit under rekonstruktionen.",
          "references": [
            "2 §"
          ]
        },
        {
          "id": "kap-3-§-4",
          "number": 4,
          "text": "Om gäldenären bestämmer att ett avtal ska fullföljas enligt 2 § ska, ifall motparten enligt avtalet är skyldig att prestera före gäldenären och tiden för motpartens fullgörelse är inne, gäldenären på motpartens begäran utan oskäligt uppehåll ställa säkerhet för sin fullgörelse. Är tiden för motpartens fullgörelse inte inne, har motparten rätt att få säkerhet endast om det av någon särskild anledning är nödvändigt för att skydda motparten mot förlust.",
          "references": [
            "2 §"
          ]
        },
        {
          "id": "kap-3-§-5",
          "number": 5,
          "text": "Motparten har rätt att häva avtalet om gäldenären inte fullgör sin prestation enligt 3 § första och andra styckena eller inte ställer säkerhet enligt 4 §.",
          "references": [
            "3 §",
            "4 §"
          ]
        },
        {
          "id": "kap-3-§-6",
          "number": 6,
          "text": "Gäldenären ska på motpartens begäran ge besked inom skälig tid om huruvida och i vilken utsträckning ett avtal ska fullföljas enligt 2 §. Om gäldenären inte lämnar något besked inom skälig tid får motparten häva avtalet. Detsamma gäller för den del av avtalet som inte ska fullföljas om gäldenären bestämmer att avtalet ska fullföljas endast till viss del.",
          "references": [
            "2 §"
          ],
          "heading": "Motpartens rätt till besked om fullföljd"
        },
        {
          "id": "kap-3-§-7",
          "number": 7,
          "text": "Om gäldenären efter beslutet om företagsrekonstruktion tar emot en prestation från en motpart, utan att gäldenären bestämmer att avtalet ska fullföljas enligt 2 §, får motparten kräva att prestationen lämnas tillbaka.\n\nOm gäldenären förfogar över prestationen på ett sådant sätt som gör att den inte kan lämnas tillbaka väsentligen oförändrad eller oförminskad, ska gäldenären anses ha bestämt att avtalet ska fullföljas i fråga om prestationen. Detsamma gäller om gäldenären utnyttjar en prestation som är sådan att den inte kan lämnas tillbaka.\n\nOm prestationen ligger utanför den löpande förvaltningen av verksamheten, ska gäldenären anses ha bestämt att avtalet ska fullföljas endast ifall rekonstruktören vid tidpunkten för förfogandet eller utnyttjandet kände till eller borde ha känt till att prestationen tagits emot eller det avtal som prestationen avser.",
          "references": [
            "2 §"
          ],
          "heading": "Motpartens skydd för prestationer som gäldenären tar emot under företagsrekonstruktionen"
        },
        {
          "id": "kap-3-§-8",
          "number": 8,
          "text": "Bestämmelserna i 7 § andra stycket gäller inte nyttjande av en hyreslokal som sker under den första månaden efter beslutet om företagsrekonstruktion.",
          "references": [
            "7 §"
          ]
        },
        {
          "id": "kap-3-§-9",
          "number": 9,
          "text": "Gäldenären får med rekonstruktörens samtycke säga upp ett varaktigt avtal till den del som det inte ska fullföljas enligt 2 § att upphöra efter tre månader. Gäldenären är skyldig att ersätta den skada som uppsägningen orsakar motparten. Motpartens fordran på skadestånd ska anses ha uppkommit före beslutet om företagsrekonstruktion.\n\nFörsta stycket gäller inte om motpartens rätt till gäldenärens prestationer gäller mot gäldenärens borgenärer.",
          "references": [
            "2 §"
          ],
          "heading": "Gäldenärens rätt att säga upp varaktiga avtal"
        },
        {
          "id": "kap-3-§-10",
          "number": 10,
          "text": "Ett avtalsvillkor som inskränker gäldenärens rätt enligt 1-9 §§ är utan verkan.\n\nDetsamma gäller ett sådant villkor som ger gäldenärens motpart rätt att hålla inne sin prestation, häva avtalet eller på annat sätt ändra avtalet till gäldenärens nackdel på grund av ansökan eller beslutet om företagsrekonstruktion eller planförhandling eller de ekonomiska svårigheter hos gäldenären som legat till grund för ansökan om företagsrekonstruktion.",
          "references": [
            "1-9 §§"
          ],
          "heading": "Avtalsvillkor som avviker från lagen"
        },
        {
          "id": "kap-3-§-11",
          "number": 11,
          "text": "Bestämmelserna i 1-10 §§ gäller inte för en borgenär som innehar finansiella instrument, valuta eller sådana fordringar som avses i 8 kap. 10 § andra stycket konkurslagen (1987:672) som säkerhet.\n\nI 5 kap. 1 § andra stycket lagen (1991:980) om handel med finansiella instrument finns bestämmelser om slutavräkningsklausuler.",
          "references": [
            "1-10 §§",
            "8 kap. 10 §",
            "5 kap. 1 §"
          ],
          "heading": "Undantag för vissa fordringar och avtal"
        },
        {
          "id": "kap-3-§-12",
          "number": 12,
          "text": "Bestämmelserna i 1-10 §§ gäller inte för anställningsavtal.\n\nOm en arbetstagare fortsätter att fullgöra sina åtaganden enligt ett anställningsavtal med gäldenären, ska arbetstagarens fordran på lön eller annan ersättning för arbete som utförs senare än en månad efter beslutet om företagsrekonstruktion anses ha uppkommit under rekonstruktionen.",
          "references": [
            "1-10 §§"
          ],
          "heading": "Anställningsavtal"
        }
      ]
    },
    {
      "id": "kap-4",
      "number": 4,
      "title": "Planförhandling under företagsrekonstruktionen",
      "sections": [
        {
          "id": "kap-4-§-1",
          "number": 1,
          "text": "Gäldenären får i ett ärende om företagsrekonstruktion begära att rätten beslutar om förhandling om en rekonstruktionsplan (planförhandling).\n\nRekonstruktören får begära att rätten beslutar om planförhandling om gäldenärens begäran om planförhandling inte leder till att en rekonstruktionsplan blir fastställd.",
          "references": [],
          "heading": "Begäran om planförhandling"
        },
        {
          "id": "kap-4-§-2",
          "number": 2,
          "text": "En begäran om planförhandling ska vara skriftlig och innehålla\n   1. ett förslag till rekonstruktionsplan,\n   2. uppgift om huruvida säkerhet har ställts för det som gäldenären erbjuder i betalning enligt rekonstruktionsplanen och vad den i så fall består av, och\n   3. bevis om att rekonstruktionsplanen har sänts till de berörda parter som anges i planen.\n\nGäldenären ska betala förskott till staten för kostnaden för handläggningen av frågan om rekonstruktionsplanens fastställande.",
          "references": []
        },
        {
          "id": "kap-4-§-3",
          "number": 3,
          "text": "I en planförhandling deltar borgenärer vilkas fordringar uppkommit före beslutet om företagsrekonstruktion samt aktieägare och andra med ett ägarintresse i gäldenären eller gäldenärens verksamhet, under förutsättning att deras fordringar eller rättigheter berörs direkt av en rekonstruktionsplan (berörda parter).",
          "references": [],
          "heading": "Deltagare i en planförhandling"
        },
        {
          "id": "kap-4-§-4",
          "number": 4,
          "text": "En rekonstruktionsplan ska innehålla de åtgärder som är nödvändiga för att komma till rätta med gäldenärens ekonomiska svårigheter och säkerställa att den verksamhet som gäldenären bedriver, helt eller delvis ska kunna fortsättas av gäldenären eller någon annan.",
          "references": [],
          "heading": "Allmänt om rekonstruktionsplanen"
        },
        {
          "id": "kap-4-§-5",
          "number": 5,
          "text": "I rekonstruktionsplanen ska de berörda parterna delas in i en eller flera av följande grupper:\n   1. borgenärer vars fordringar är förenade med förmånsrätt, säkerhetsrätt eller kvittningsrätt,\n   2. borgenärer med offentligrättsliga fordringar, om fordran inte är sådan som avses i 1 eller 3,\n   3. borgenärer med efterställda fordringar,\n   4. borgenärer med andra fordringar än de som avses i 1-3, och\n   5. aktieägare eller andra som har ett ägarintresse i gäldenären eller gäldenärens verksamhet.\n\nBerörda parter i de grupper som anges i första stycket får i sin tur delas in i ytterligare grupper om det är motiverat utifrån att de har likvärdiga intressen.",
          "references": []
        },
        {
          "id": "kap-4-§-6",
          "number": 6,
          "text": "I rekonstruktionsplanen ska berörda parter i samma grupp behandlas lika i proportion till deras respektive fordran eller rättighet, medan berörda parter i olika grupper kan föreslås olika villkor och ges olika rätt.",
          "references": []
        },
        {
          "id": "kap-4-§-7",
          "number": 7,
          "text": "En rekonstruktionsplan ska innehålla uppgift om\n   1. namn, personnummer eller organisationsnummer och kontaktuppgifter,\n   2. vem som förordnats till rekonstruktör,\n   3. arbetstagarnas ställning och planens övergripande konsekvenser för anställningar med beaktande av arbetstagarnas kollektiva och individuella rättigheter samt vilka åtgärder som vidtagits för att informera och samråda med arbetstagarrepresentanter,\n   4. de berörda parterna och deras fordringar eller rättigheter,\n   5. de berörda parternas gruppindelning och skälen för indelningen samt värdena av fordringarna och rättigheterna i varje grupp,\n   6. de borgenärer och de aktieägare och andra med ett ägarintresse i gäldenären eller gäldenärens verksamhet som inte berörs av rekonstruktionsplanen samt en redogörelse för varför planen inte ska beröra dem,\n   7. rekonstruktionsåtgärderna, inklusive en eventuell skulduppgörelse, och tidpunkten eller tidsperioden för de föreslagna åtgärderna, och\n   8. nytt finansiellt stöd som tillhandahålls i syfte att genomföra planen (ny finansiering) och skälen till att den nya finansieringen är nödvändig för att genomföra planen.",
          "references": [],
          "heading": "Innehållet i en rekonstruktionsplan"
        },
        {
          "id": "kap-4-§-8",
          "number": 8,
          "text": "Till rekonstruktionsplanen ska bifogas\n   1. en berättelse av rekonstruktören som redogör för\n      a) vilka åtgärder som vidtagits under rekonstruktionen,\n      b) gäldenärens ekonomiska situation och orsakerna till och omfattningen av de ekonomiska svårigheterna,\n      c) den utdelning som kan förväntas i en konkurs,\n      d) om gäldenären har gjort sig av med egendom under sådana förhållanden att den kan bli föremål för återvinning,\n      e) om det finns skälig anledning att anta att gäldenären har gjort sig skyldig till brott mot sina borgenärer och i så fall grunden för detta, och\n      f) hur gäldenären har fullgjort sin bokföringsskyldighet,\n   2. en förteckning över gäldenärens tillgångar och skulder vid beslutet om företagsrekonstruktion och begäran om planförhandling, som har upprättats av rekonstruktören enligt 9 och 10 §§,\n   3. senaste årsredovisningen eller årsbokslutet, och\n   4. ett yttrande av rekonstruktören som innehåller en bedömning av om rekonstruktionsplanen bör antas av de berörda parterna och som förklarar varför planen har rimliga utsikter att säkra verksamhetens livskraft och förebygga insolvens.",
          "references": [
            "9 och 10 §§"
          ]
        },
        {
          "id": "kap-4-§-9",
          "number": 9,
          "text": "I förteckningen enligt 8 § 2 ska tillgångarna tas upp till marknadsvärdet vid den tidpunkt då förteckningen upprättas.\n\nVärdet ska bestämmas med utgångspunkten att gäldenärens verksamhet helt eller delvis ska fortsätta. Dessutom ska ett värde bestämmas med utgångspunkt från det pris till vilket tillgångarna hade kunnat säljas i en konkurs.\n\nOm möjligt ska det även lämnas en specificerad uppgift om de värden som i bokföringshandlingarna har angetts för tillgångarna eller, när en sådan värdering inte har gjorts, om anskaffningskostnaden.\n\nRänta på en berörd parts fordran ska inte beräknas längre än till dagen för beslutet om företagsrekonstruktion. En fordran i utländsk valuta ska beräknas efter den kurs som gällde nämnda dag.",
          "references": [
            "8 §"
          ],
          "heading": "Förteckning över tillgångar och skulder"
        },
        {
          "id": "kap-4-§-10",
          "number": 10,
          "text": "I förteckningen enligt 8 § 2 ska det anges om en borgenär har förmånsrätt och grunden till det.\n\nOm värdet av egendom som en borgenär har särskild förmånsrätt eller säkerhet genom återtaganderätt i bedöms understiga borgenärens fordran, ska säkerhetens värde anges i förteckningen. Detsamma gäller för egendom som är föremål för finansiell leasing.\n\nOm en borgenärs fordran är förenad med allmän förmånsrätt som vid en konkurs, om den hade beslutats vid tiden för beslutet om företagsrekonstruktion, inte skulle ha täckt hela borgenärens fordran, ska det anges hur stor del av fordringen som täcks av förmånsrätten.\n\nOm någon har gjort en anmärkning ska det anges.",
          "references": [
            "8 §"
          ]
        },
        {
          "id": "kap-4-§-11",
          "number": 11,
          "text": "Om en begäran om planförhandling inte uppfyller kraven i 2 § eller om rekonstruktionsplanen inte uppfyller kraven i 7 och 8 §§ ska sökanden föreläggas att avhjälpa bristen. För det fall sökanden inte följer föreläggandet ska begäran om planförhandling avvisas.",
          "references": [
            "2 §",
            "7 och 8 §§"
          ],
          "heading": "Avvisning"
        },
        {
          "id": "kap-4-§-12",
          "number": 12,
          "text": "Om begäran om planförhandling inte avvisas, ska rätten genast besluta om planförhandling. Rätten ska samtidigt\n   1. bestämma tidpunkt för ett sammanträde med de berörda parterna inför rätten (plansammanträde),\n   2. kalla gäldenären, rekonstruktören och de berörda parterna till sammanträdet, och\n   3. kungöra beslutet i Post- och Inrikes Tidningar och i övrigt på det sätt som regeringen föreskriver.",
          "references": [],
          "heading": "Beslut om planförhandling"
        },
        {
          "id": "kap-4-§-13",
          "number": 13,
          "text": "Om någon vill delta i planförhandlingen med en fordran eller en rättighet som inte har tagits med i förslaget till rekonstruktionsplan och inte heller senare blivit känd, ska han eller hon skriftligen anmäla fordringen eller rättigheten hos rekonstruktören senast en vecka före plansammanträdet. Görs anmälan senare, får det inte leda till att omröstningen vid plansammanträdet skjuts upp.",
          "references": [],
          "heading": "Senare anmälda fordringar eller rättigheter"
        },
        {
          "id": "kap-4-§-14",
          "number": 14,
          "text": "Rekonstruktören, gäldenären eller en berörd part får anmärka mot följande uppgifter i rekonstruktionsplanen:\n   1. fordringar och rättigheter, och\n   2. valet av berörda parter och gruppindelningen.\n\nEn anmärkning ska göras skriftligen hos rekonstruktören i så god tid som möjligt och i vart fall före omröstningen vid plansammanträdet.\n\nRekonstruktören ska lämna gjorda anmärkningar till rätten och skyndsamt underrätta gäldenären och den som anmärkningen kan påverka.",
          "references": [],
          "heading": "Anmärkningar mot rekonstruktionsplanen"
        },
        {
          "id": "kap-4-§-15",
          "number": 15,
          "text": "Ett plansammanträde ska hållas tidigast tre och senast fem veckor efter beslutet om planförhandling.\n\nGäldenären bör inställa sig personligen vid plansammanträdet. Vid sammanträdet ska gäldenären till rätten, rekonstruktören och de berörda parterna lämna de upplysningar om gäldenärens ekonomiska situation som de begär. Kan gäldenären inte infinna sig personligen, bör denne utse ett ombud.\n\nRekonstruktören ska tillhandahålla en förteckning över de berörda parterna och över de grupper som de berörda parterna har delats in i, med uppgift om de värden för vilka rösträtt får utövas. Förteckningen ska även innehålla gjorda anmärkningar.",
          "references": [],
          "heading": "Plansammanträdet"
        },
        {
          "id": "kap-4-§-16",
          "number": 16,
          "text": "En rekonstruktionsplan får inte återtas eller ändras utan godkännande av rätten. En begäran om detta ska göras senast vid plansammanträdet innan omröstning sker.\n\nOm rätten har godkänt en ändring av rekonstruktionsplanen, får prövningen av planen skjutas upp till ett fortsatt sammanträde inom tre veckor. Om ändringen inte medför att rekonstruktionsplanen blir sämre för de berörda parterna, får prövningen dock skjutas upp endast om det finns särskilda skäl.",
          "references": []
        },
        {
          "id": "kap-4-§-17",
          "number": 17,
          "text": "Vid plansammanträdet ska rätten pröva valet av berörda parter och den gruppindelning som gjorts i rekonstruktionsplanen. Om rätten inte godkänner valet av berörda parter eller gruppindelningen får rätten göra nödvändiga ändringar av rekonstruktionsplanen eller besluta att omröstningen enligt andra stycket ska skjutas upp till fortsatt sammanträde inom tre veckor.\n\nEfter att rätten godkänt valet av berörda parter och gruppindelningen ska de berörda parterna rösta om rekonstruktionsplanen. En anmärkning som har gjorts mot en fordran eller en rättighet hindrar inte att den berörda parten deltar med fordringen eller rättigheten i omröstningen.",
          "references": []
        },
        {
          "id": "kap-4-§-18",
          "number": 18,
          "text": "Om utgången av omröstningen är beroende av om en anmärkning mot en fordran eller en rättighet godtas eller inte, ska rätten vid sammanträdet utreda tvistefrågan och verka för en förlikning. De närvarande får med bindande verkan för dem som har uteblivit medge att en anmärkning förfaller eller inskränks eller uppdra åt rekonstruktören att ingå förlikning med dem som berörs. Om en förlikning inte kan träffas, ska rätten pröva anmärkningarna eller så många av dem att utgången av omröstningen blir densamma, oavsett om övriga anmärkningar godkänns eller inte.\n\nEn förlikning om en framställd anmärkning får inte ingås på annat sätt än som anges i första stycket utan samtycke av alla vars rätt är beroende av förlikningen.",
          "references": []
        },
        {
          "id": "kap-4-§-19",
          "number": 19,
          "text": "Om det finns särskilda skäl får rätten, i annat fall än som anges i 16 § andra stycket eller 17 § första stycket, besluta att skjuta upp omröstningen till fortsatt sammanträde inom tre veckor.",
          "references": [
            "16 §",
            "17 §"
          ]
        },
        {
          "id": "kap-4-§-20",
          "number": 20,
          "text": "En rekonstruktionsplan ska anses antagen av de berörda parterna, om i varje grupp minst två tredjedelar av de röstande har godtagit planen, och deras fordringar eller rättigheter uppgår till minst två tredjedelar av de fordringar eller rättigheter för vilka rösträtt får utövas.",
          "references": [],
          "heading": "Antagande av en rekonstruktionsplan"
        },
        {
          "id": "kap-4-§-21",
          "number": 21,
          "text": "Om både en borgenär och en borgensman eller någon annan som förutom gäldenären ansvarar för borgenärens fordran vill rösta för denna, har de tillsammans en röst, som beräknas efter borgenärens fordran. Kan de inte enas, gäller borgenärens mening, om inte de andra löser ut borgenären eller ställer betryggande säkerhet för fordringen.",
          "references": []
        },
        {
          "id": "kap-4-§-22",
          "number": 22,
          "text": "Om en rekonstruktionsplan har antagits, ska rätten så snart som möjligt pröva om planen ska fastställas.",
          "references": [],
          "heading": "Fastställelse av en rekonstruktionsplan"
        },
        {
          "id": "kap-4-§-23",
          "number": 23,
          "text": "Rätten ska vägra att fastställa rekonstruktionsplanen om\n   1. berörda parter inom samma grupp inte behandlas lika i proportion till deras respektive fordran eller rättighet,\n   2. planen inte har rimliga utsikter att förhindra att gäldenären blir insolvent eller säkra verksamhetens livskraft,\n   3. det finns skälig anledning att anta att gäldenären i hemlighet har gynnat någon berörd part för att inverka på planförhandlingen eller att något annat svek har inträffat vid planförhandlingen,\n   4. planen strider mot lag eller annan författning eller är uppenbart till skada för berörda parter, eller\n   5. ärendet inte har handlagts på föreskrivet sätt och felet kan ha inverkat på planförhandlingens utgång.\n\nOm rekonstruktionsplanen föreskriver ny finansiering ska planen fastställas endast om den nya finansieringen är nödvändig för att genomföra planen och inte otillbörligen skadar borgenärernas intressen.\n\nOm rätten vägrar att fastställa planen med stöd av första stycket 5, får rätten besluta att de berörda parterna ska rösta om planen vid ett nytt plansammanträde.",
          "references": []
        },
        {
          "id": "kap-4-§-24",
          "number": 24,
          "text": "Rätten ska efter invändning av en berörd part också vägra att fastställa rekonstruktionsplanen om det ekonomiska utfallet för den berörda parten blir sämre genom planen än vad det hade blivit vid gäldenärens konkurs.\n\nRätten får dessutom efter invändning av en berörd part vägra att fastställa rekonstruktionsplanen om den på något annat sätt är till skada för den berörda parten, det inte finns betryggande säkerhet för planens fullgörande, eller om det annars finns särskild anledning att inte fastställa planen.",
          "references": []
        },
        {
          "id": "kap-4-§-25",
          "number": 25,
          "text": "Trots att en rekonstruktionsplan inte antagits, ska den på begäran av gäldenären, rekonstruktören eller en berörd part fastställas av rätten, om\n   1. det inte finns något skäl att vägra fastställelse enligt 23 eller 24 §,\n   2. planen har godkänts av fler än hälften av grupperna med berörda parter och\n      a) minst en av dessa grupper utgörs av borgenärer vars fordringar är förenade med förmånsrätt, säkerhetsrätt eller kvittningsrätt, eller\n      b) minst två av dessa grupper utgörs av borgenärer som kan förväntas få betalt vid gäldenärens konkurs,\n   3. den eller de grupper av berörda parter som röstat mot planen behandlas minst lika fördelaktigt som andra grupper som vid gäldenärens konkurs har samma prioritet,\n   4. den eller de grupper av berörda parter som röstat mot planen får sina fordringar fullt tillgodosedda med samma eller likvärdiga medel, om en grupp som vid gäldenärens konkurs har lägre prioritet ska få någon betalning eller behålla någon rättighet enligt planen, och\n   5. ingen grupp av berörda parter enligt planen får eller behåller mer än det fulla värdet av sina fordringar eller rättigheter.",
          "references": [
            "24 §"
          ],
          "heading": "Fastställelse av en rekonstruktionsplan som inte antagits"
        },
        {
          "id": "kap-4-§-26",
          "number": 26,
          "text": "Om det finns synnerliga skäl får rekonstruktionsplanen fastställas även om den avviker från 25 § första stycket 3 eller 4.",
          "references": [
            "25 §"
          ]
        },
        {
          "id": "kap-4-§-27",
          "number": 27,
          "text": "För att rätten ska fastställa en rekonstruktionsplan enligt 25 eller 26 § krävs gäldenärens samtycke om gäldenären har färre än 250 anställda och\n   1. en omsättning som inte överstiger 50 miljoner euro per år, eller\n   2. en balansomslutning som inte överstiger 43 miljoner euro per år.",
          "references": [
            "26 §"
          ]
        },
        {
          "id": "kap-4-§-28",
          "number": 28,
          "text": "Om en berörd part invänder att det finns hinder mot att fastställa rekonstruktionsplanen enligt 24 § första stycket eller 25 § första stycket 2 b, ska rätten i samband med prövningen av invändningen göra en värdering som fastställer det ekonomiska utfallet för berörda parter om gäldenären försätts i konkurs.",
          "references": [
            "24 §",
            "25 §"
          ],
          "heading": "Värdering av gäldenärens verksamhet"
        },
        {
          "id": "kap-4-§-29",
          "number": 29,
          "text": "En fastställd rekonstruktionsplan är bindande för gäldenären och alla berörda parter samt för gäldenärens motpart i avtal om ny finansiering.\n\nOm rekonstruktionsplanen innehåller en skulduppgörelse har en borgenär, vars fordran inte var känd när rekonstruktionsplanen fastställdes, endast rätt till betalning motsvarande vad den grupp som borgenären skulle ha delats in i har erhållit, om borgenären varit känd.",
          "references": [],
          "heading": "Verkan av en fastställd rekonstruktionsplan"
        },
        {
          "id": "kap-4-§-30",
          "number": 30,
          "text": "En borgenär som har godtagit en rekonstruktionsplan som innehåller en skulduppgörelse förlorar inte därigenom sin rätt mot en borgensman eller någon annan som förutom gäldenären svarar för fordringen.",
          "references": []
        },
        {
          "id": "kap-4-§-31",
          "number": 31,
          "text": "Om en fastställd rekonstruktionsplan innehåller uppgift om ändring av aktiekapitalet har planen samma verkan som ett beslut av bolagsstämman enligt 11 kap. 2 §, 16 kap. 2 eller 3 § eller 20 kap. 3 § aktiebolagslagen (2005:551).\n\nOm en fastställd rekonstruktionsplan innehåller sådana ändringar av bolagsordningen som enligt 11 kap. 2 § andra stycket eller 20 kap. 4 § första stycket aktiebolagslagen krävs för att genomföra en ändring av aktiekapitalet, har planen samma verkan som ett beslut av bolagsstämman.\n\nI en rekonstruktionsplan får avvikelse göras från det som anges om aktieägarnas företrädesrätt i 13 kap. 1 § första stycket, 14 kap. 1 § första stycket och 15 kap. 1 § första stycket aktiebolagslagen.",
          "references": [
            "11 kap. 2 §",
            "3 §",
            "20 kap. 3 §",
            "20 kap. 4 §",
            "13 kap. 1 §",
            "14 kap. 1 §",
            "15 kap. 1 §"
          ],
          "heading": "Förhållandet till aktiebolagslagen"
        },
        {
          "id": "kap-4-§-32",
          "number": 32,
          "text": "Om det i en rekonstruktionsplan föreslås en ökning eller minskning av aktiekapitalet gäller det som anges i 12 kap. 3 §, 13 kap. 3 §, 14 kap. 3 §, 15 kap. 3 § och 20 kap. 6 § aktiebolagslagen (2005:551) om styrelsens skyldigheter att upprätta förslag till beslut i stället för den som begär planförhandling.",
          "references": [
            "12 kap. 3 §",
            "13 kap. 3 §",
            "14 kap. 3 §",
            "15 kap. 3 §",
            "20 kap. 6 §"
          ]
        },
        {
          "id": "kap-4-§-33",
          "number": 33,
          "text": "På begäran av en berörd part ska rätten, om det finns skäl för det, förordna rekonstruktören eller någon annan lämplig person att utöva tillsyn över att gäldenären fullgör sina åtaganden enligt rekonstruktionsplanen. Om det behövs, ska även en ersättare för tillsynspersonen förordnas.\n\nGäldenären ska ge tillsynspersonen de uppgifter som han eller hon begär och följa de anvisningar som tillsynspersonen lämnar.\n\nI fråga om entledigande av en tillsynsperson tillämpas bestämmelserna om entledigande av rekonstruktör i 2 kap. 17 §.",
          "references": [
            "2 kap. 17 §"
          ],
          "heading": "Förordnande av en tillsynsperson"
        },
        {
          "id": "kap-4-§-34",
          "number": 34,
          "text": "På begäran av en berörd part eller en tillsynsperson får rätten, helt eller delvis, upphäva en fastställd rekonstruktionsplan, om gäldenären\n   1. har gjort sig skyldig till oredlighet mot borgenärer,\n   2. har gjort sig skyldig till uppsåtligt försvårande av konkurs eller exekutiv förrättning,\n   3. i hemlighet har gynnat någon berörd part för att inverka på utgången av planförhandlingen,\n   4. har åsidosatt sina skyldigheter enligt 33 § andra stycket, eller\n   5. på något annat sätt väsentligen har brutit mot sina skyldigheter enligt rekonstruktionsplanen.\n\nOm hela eller delar av rekonstruktionsplanen upphävs har gäldenären och de berörda parterna den rätt som hade gällt om planen inte blivit fastställd. Rättshandlingar som redan har företagits ska dock bestå.",
          "references": [
            "33 §"
          ],
          "heading": "Upphävande av en fastställd rekonstruktionsplan"
        }
      ]
    },
    {
      "id": "kap-5",
      "number": 5,
      "title": "Återvinning och kvittning under företagsrekonstruktionen",
      "sections": [
        {
          "id": "kap-5-§-1",
          "number": 1,
          "text": "Sedan beslut meddelats om företagsrekonstruktion tillämpas bestämmelserna i konkurslagen (1987:672) om återvinning i konkurs, om en rekonstruktionsplan som innehåller en skulduppgörelse därefter fastställs.\n\nOm en återvinningstalan avser förmånsrätt eller betalning som vunnits genom utmätning får rätten besluta att fortsatt verkställighet i utsökningsmålet tills vidare inte får ske.",
          "references": [],
          "heading": "Återvinning"
        },
        {
          "id": "kap-5-§-2",
          "number": 2,
          "text": "Talan om återvinning får väckas av rekonstruktören eller av en berörd part. Talan ska väckas före plansammanträdet och får inte slutligt prövas innan rekonstruktionsplanen har blivit fastställd. En berörd part som vill väcka talan ska underrätta rekonstruktören. Om så inte har skett, får den berörda partens talan inte tas upp till prövning.\n\nEn återvinningstalan ska avvisas om\n   1. företagsrekonstruktionen upphör utan att en rekonstruktionsplan fastställts, och\n   2. gäldenären inte försätts i konkurs efter en ansökan som gjorts inom tre veckor från det att företagsrekonstruktionen upphörde.",
          "references": []
        },
        {
          "id": "kap-5-§-3",
          "number": 3,
          "text": "Vad som vinns genom en återvinningstalan ska, sedan kärandens kostnader har ersatts, fördelas enligt grunderna för skulduppgörelsen om något annat inte har angetts i rekonstruktionsplanen. En svarande som med anledning av kärandens talan kan få en fordran mot gäldenären deltar med fordringen i planförhandlingen och har rätt att avräkna den utdelning som tillkommer svaranden på vad denne annars skulle ha betalat.\n\nRätten får besluta om särskild förvaltning av det som enligt första stycket ska tillkomma de berörda parterna, om en av dessa eller gäldenären begär det i återvinningsmålet. Egendom som har satts under sådan förvaltning får utmätas endast om rekonstruktionsplanen har upphävts.",
          "references": []
        },
        {
          "id": "kap-5-§-4",
          "number": 4,
          "text": "En borgenär som hade en fordran mot gäldenären vid beslutet om företagsrekonstruktion får, även om fordringen inte är förfallen till betalning, använda den till kvittning mot en fordran som gäldenären då hade mot borgenären. Detta gäller dock inte om kvittning är utesluten på grund av någon av fordringarnas beskaffenhet eller undantagen enligt 5 och 6 §§.\n\nGäldenärens fordran på betalning ska anses ha uppkommit under rekonstruktionen, om den gäller en naturaprestation enligt ett avtal som gäldenären har bestämt ska fullföljas enligt 3 kap. 2 §.",
          "references": [
            "5 och 6 §§",
            "3 kap. 2 §"
          ],
          "heading": "Kvittning"
        },
        {
          "id": "kap-5-§-5",
          "number": 5,
          "text": "Om en fordran mot gäldenären har förvärvats genom överlåtelse från tredje man senare än tre månader före ansökan om företagsrekonstruktion, får den inte användas till kvittning mot en fordran som gäldenären hade när borgenären förvärvade sin fordran, om förvärvet inte med hänsyn till omständigheterna kan anses som ordinärt.\n\nFörsta stycket gäller också om fordran mot gäldenären har förvärvats tidigare och borgenären då hade skälig anledning att anta att gäldenären var på obestånd.\n\nI fråga om dödsbo räknas tiden som anges i första stycket från ansökan om boets avträdande till förvaltning av boutredningsman, under förutsättning att en ansökan om företagsrekonstruktion följt inom tre månader från det att en boutredningsman förordnats.",
          "references": []
        },
        {
          "id": "kap-5-§-6",
          "number": 6,
          "text": "En borgenär som har satt sig i skuld till gäldenären under sådana omständigheter att det är att jämställa med betalning med annat än sedvanliga betalningsmedel får inte kvitta i den utsträckning sådan betalning hade kunnat bli föremål för återvinning enligt 1-3 §§.",
          "references": [
            "1-3 §§"
          ]
        },
        {
          "id": "kap-5-§-7",
          "number": 7,
          "text": "En fordran på ersättning som en borgensman eller någon annan har med anledning av en förpliktelse som han eller hon har infriat ska vid tillämpning av 4-6 §§ anses ha förvärvats när hans eller hennes förpliktelse grundades.",
          "references": [
            "4-6 §§"
          ]
        },
        {
          "id": "kap-5-§-8",
          "number": 8,
          "text": "Om gäldenären efter beslutet om företagsrekonstruktion överlåter en fordran och en borgenär därigenom förlorar sin rätt till kvittning, ska borgenärens fordran så långt den hade kunnat infrias genom kvittning anses ha uppkommit under rekonstruktionen.",
          "references": []
        }
      ]
    },
    {
      "id": "kap-6",
      "number": 6,
      "title": "Företagsrekonstruktionens upphörande",
      "sections": [
        {
          "id": "kap-6-§-1",
          "number": 1,
          "text": "Rätten ska besluta att företagsrekonstruktionen ska upphöra, om\n   1. syftet med företagsrekonstruktionen kan anses uppnått,\n   2. gäldenären begär det och något beslut om planförhandling inte har meddelats,\n   3. rekonstruktören begär det,\n   4. syftet med företagsrekonstruktionen inte kan antas bli uppnått,\n   5. det finns sådana brister eller fel i gäldenärens bokföring att rörelsens förlopp, ekonomiska resultat eller ställning i huvudsak inte går att bedöma,\n   6. det skulle vara oskäligt mot en eller flera borgenärer eller grupper av borgenärer ifall företagsrekonstruktionen fortsätter, eller\n   7. rekonstruktören entledigas och någon ny rekonstruktör inte utses.\n\nOm gäldenären försätts i konkurs upphör företagsrekonstruktionen.",
          "references": []
        },
        {
          "id": "kap-6-§-2",
          "number": 2,
          "text": "I andra fall än som avses i 1 § ska rätten besluta att företagsrekonstruktionen ska upphöra när tre månader har förflutit från dagen för beslutet om företagsrekonstruktion.\n\nOm det finns särskilda skäl får dock rätten på begäran av gäldenären, rekonstruktören eller en borgenär medge att företagsrekonstruktionen får pågå under ytterligare högst tre månader. Om det finns synnerliga skäl får rätten under motsvarande förutsättning förlänga tiden med ytterligare högst tre månader i taget.\n\nVid bedömningen av om en förlängning ska beslutas ska rätten särskilt beakta vilka framsteg som har gjorts i förhandlingarna om rekonstruktionsplanen, och hur en fortsättning av företagsrekonstruktionen skulle påverka borgenärernas rättigheter eller intressen.",
          "references": [
            "1 §"
          ]
        },
        {
          "id": "kap-6-§-3",
          "number": 3,
          "text": "En företagsrekonstruktion får inte pågå under längre tid än sammanlagt tolv månader, om inte rätten dessförinnan har beslutat om planförhandling. I så fall ska företagsrekonstruktionen upphöra senast femton månader efter beslutet om företagsrekonstruktion.\n\nReglerna i 2 kap. 23 och 24 §§ och 3 kap. 1 § denna lag och 2 kap. 10 a § konkurslagen (1987:672) gäller aldrig längre än tolv månader från beslutet om företagsrekonstruktion.",
          "references": [
            "2 kap. 23 och 24 §§",
            "3 kap. 1 §",
            "2 kap. 10 a §"
          ]
        },
        {
          "id": "kap-6-§-4",
          "number": 4,
          "text": "Innan rätten fattar beslut enligt 1 § första stycket eller 2 § andra stycket ska gäldenären, rekonstruktören, tillsynsmyndigheten och de borgenärer som infunnit sig till borgenärssammanträdet enligt 2 kap 13 § andra stycket ges tillfälle att yttra sig. Om en borgenärskommitté har utsetts, ska även den ges tillfälle att yttra sig.",
          "references": [
            "1 §",
            "2 §",
            "13 §"
          ]
        }
      ]
    },
    {
      "id": "kap-7",
      "number": 7,
      "title": "Tillsyn över rekonstruktörer",
      "sections": [
        {
          "id": "kap-7-§-1",
          "number": 1,
          "text": "Kronofogdemyndigheten är tillsynsmyndighet.\n\nTillsynsmyndighetens uppgifter framgår av 2 kap. 13 och 17 §§, 6 kap. 4 § och 9 kap. 4 §.",
          "references": [
            "2 kap. 13 och 17 §§",
            "6 kap. 4 §",
            "9 kap. 4 §"
          ]
        }
      ]
    },
    {
      "id": "kap-8",
      "number": 8,
      "title": "Straff och skadestånd",
      "sections": [
        {
          "id": "kap-8-§-1",
          "number": 1,
          "text": "Om en borgenärs ansökan om företagsrekonstruktion inte bifalls och om borgenären när ansökan gavs in saknade skälig anledning att anta att gäldenären hade sådana ekonomiska svårigheter som avses i 2 kap. 10 § 1, ska borgenären ersätta gäldenären för den skada som skäligen kan anses ha orsakats gäldenären genom ansökan och dess handläggning.\n\nTalan om skadestånd enligt första stycket ska väckas vid den tingsrätt som handlägger eller har handlagt ärendet om företagsrekonstruktion.",
          "references": [
            "2 kap. 10 §"
          ],
          "heading": "Skadestånd"
        },
        {
          "id": "kap-8-§-2",
          "number": 2,
          "text": "En rekonstruktör ska ersätta de skador som han eller hon vid fullgörandet av sitt uppdrag uppsåtligen eller av oaktsamhet tillfogar gäldenären, en borgenär eller en berörd part.\n\nSkadeståndet kan sättas ned efter vad som är skäligt med hänsyn till handlingens beskaffenhet, skadans storlek och omständigheterna i övrigt.\n\nOm flera rekonstruktörer ska ersätta samma skada, svarar de solidariskt för skadeståndet i den utsträckning inte skadeståndsskyldigheten har satts ned för någon av dem enligt andra stycket. Det som någon har betalat i skadestånd får sökas åter av de andra efter vad som är skäligt med hänsyn till omständigheterna.",
          "references": []
        },
        {
          "id": "kap-8-§-3",
          "number": 3,
          "text": "En talan om skadestånd mot en rekonstruktör ska väckas inom tre månader från den dag då beslutet om att företagsrekonstruktionen ska upphöra fick laga kraft.\n\nTalan ska väckas vid den tingsrätt som handlägger eller har handlagt ärendet om företagsrekonstruktion.",
          "references": []
        },
        {
          "id": "kap-8-§-4",
          "number": 4,
          "text": "En berörd part som för sin röst vid ett plansammanträde enligt 4 kap. har betingat sig någon särskild förmån av gäldenären döms till böter eller fängelse i högst ett år.",
          "references": [],
          "heading": "Straff"
        },
        {
          "id": "kap-8-§-5",
          "number": 5,
          "text": "Åtal mot en gäldenär för brott mot borgenärer får väckas vid den tingsrätt som handlägger eller har handlagt ärendet om företagsrekonstruktion. Detsamma gäller för åtal mot en berörd part för brott som avses i 4 §.",
          "references": [
            "4 §"
          ]
        }
      ]
    },
    {
      "id": "kap-9",
      "number": 9,
      "title": "Övriga bestämmelser",
      "sections": [
        {
          "id": "kap-9-§-1",
          "number": 1,
          "text": "Om inte något annat föreskrivs, gäller lagen (1996:242) om domstolsärenden för rättens handläggning enligt denna lag.",
          "references": [],
          "heading": "Handläggningen av ärenden om företagsrekonstruktion"
        },
        {
          "id": "kap-9-§-2",
          "number": 2,
          "text": "Beslut om företagsrekonstruktion, planförhandling, fastställelse av en rekonstruktionsplan och beslut att företagsrekonstruktionen ska upphöra ska gälla omedelbart, om inte annat bestämts av rätten. Detsamma gäller beslut att utse eller entlediga en rekonstruktör.",
          "references": [],
          "heading": "Överklagande"
        },
        {
          "id": "kap-9-§-3",
          "number": 3,
          "text": "Rättens beslut enligt denna lag får överklagas för sig. Detta gäller dock inte beslut i en fråga som avses i 4 kap. 16 § första stycket eller 18 § eller om en sådan ny prövning som avses i 23 § tredje stycket.\n\nI fråga om beslut om planförhandling räknas överklagandetiden från den dag då kungörelsen om beslutet var införd i Post- och Inrikes Tidningar.",
          "references": [
            "4 kap. 16 §",
            "18 §",
            "23 §"
          ]
        },
        {
          "id": "kap-9-§-4",
          "number": 4,
          "text": "Rekonstruktören har rätt till ersättning för arbete och för de utlägg som uppdraget har krävt. Arvodet får inte bestämmas till ett högre belopp än som med hänsyn till det arbete som uppdraget har krävt, den omsorg och skicklighet som det har utförts med samt näringsverksamhetens omfattning kan anses utgöra skälig ersättning för uppdraget.\n\nRekonstruktörens rätt till ersättning ska, på begäran av tillsynsmyndigheten, rekonstruktören eller gäldenären, prövas av rätten. Så länge rekonstruktionsplanen inte fullgjorts får också en berörd part vars fordran eller rättighet omfattas av planen begära en sådan prövning.\n\nTillsynsmyndigheten ska ges tillfälle att yttra sig innan rätten fattar beslut om rekonstruktörens ersättning.",
          "references": [],
          "heading": "Ersättning till rekonstruktörer och tillsynspersoner"
        },
        {
          "id": "kap-9-§-5",
          "number": 5,
          "text": "Rekonstruktören ska innan företagsrekonstruktionen upphör underrätta tillsynsmyndigheten om den ersättning som han eller hon begär för arbete och utlägg.\n\nPå begäran av tillsynsmyndigheten ska rekonstruktören tillhandahålla myndigheten en redogörelse för det arbete som uppdraget har medfört med en specificerad räkning som visar det begärda beloppets fördelning på de olika åtgärderna. Om rekonstruktören har anlitat ett sådant biträde som avses i 2 kap. 16 § tredje stycket ska det anges i redogörelsen.",
          "references": [
            "2 kap. 16 §"
          ]
        },
        {
          "id": "kap-9-§-6",
          "number": 6,
          "text": "För ersättning till en tillsynsperson gäller det som föreskrivs om rekonstruktörens rätt till ersättning i 4 §.",
          "references": [
            "4 §"
          ]
        },
        {
          "id": "kap-9-§-7",
          "number": 7,
          "text": "Gäldenären ska betala kostnaderna för handläggningen hos rätten, liksom de ersättningar som avses i 4 och 6 §§.",
          "references": [
            "4 och 6 §§"
          ],
          "heading": "Gäldenärens kostnadsansvar"
        },
        {
          "id": "kap-9-§-8",
          "number": 8,
          "text": "Gäldenären ska betala en avgift till staten för tillsynen över rekonstruktörer enligt föreskrifter som regeringen meddelar.",
          "references": [],
          "heading": "Tillsynsavgift"
        },
        {
          "id": "kap-9-§-9",
          "number": 9,
          "text": "I lagen (2017:473) med kompletterande bestämmelser till 2015 års insolvensförordning finns bestämmelser om registrering av företagsrekonstruktioner i ett insolvensregister.",
          "references": [],
          "heading": "Registrering av företagsrekonstruktioner"
        }
      ]
    }
  ],
  "transitional": [
    {
      "sfs": "2022:964",
      "text": "1. Denna lag träder i kraft den 1 augusti 2022.\n   2. Genom lagen upphävs lagen (1996:764) om företagsrekonstruktion.\n   3. Den upphävda lagen gäller dock fortfarande när ansökan om företagsrekonstruktion har gjorts före ikraftträdandet."
    }
  ]
};
