// Lönegarantiförordning (2024:1329)
// Generated by backend/build_laws_from_docx.py from the official DOCX (Regeringskansliet fulltext).
// Versions in force on 2026-10-07. Do not edit by hand - fix the parser or the source DOCX and regenerate.
// Last amended: t.o.m. SFS 2026:332

import { LegalText } from '../legalTexts';

export const lönegarantiförordning: LegalText = {
  "id": "sfs-2024-1329",
  "title": "Lönegarantiförordning (2024:1329)",
  "sfsNumber": "2024:1329",
  "department": "Arbetsmarknadsdepartementet ARM",
  "issued": "2024-12-19",
  "lastAmended": "t.o.m. SFS 2026:332",
  "chaptered": false,
  "chapters": [
    {
      "id": "kap-1",
      "number": 1,
      "title": "Lönegarantiförordning (2024:1329)",
      "sections": [
        {
          "id": "kap-1-§-1",
          "number": 1,
          "text": "Denna förordning innehåller bestämmelser om handläggning av ärenden och mål om statlig lönegaranti vid sådana insolvensförfaranden som avses i 1 § lönegarantilagen (1992:497).\n\nFörordningen är meddelad med stöd av 8 kap. 7 § regeringsformen.",
          "references": [
            "1 §",
            "8 kap. 7 §"
          ]
        },
        {
          "id": "kap-1-§-2",
          "number": 2,
          "text": "En underrättelse enligt 11 eller 12 § lönegarantilagen (1992:497) ska innehålla uppgift om\n   1. konkursgäldenären,\n   2. dagen för konkursbeslutet och vilken domstol som har meddelat beslutet,\n   3. arbetstagaren,\n   4. den fordran som arbetstagaren har mot konkursgäldenären och i vilken omfattning den ska betalas av garantin,\n   5. vilken arbetstagarorganisation som arbetstagaren tillhör, om den uppgiften behövs,\n   6. huruvida arbetstagaren har ändrad beräkning av preliminär skatt eller utmätning av lön, och\n   7. huruvida arbetstagaren ska utföra arbete för konkursgäldenären under uppsägningstiden.",
          "references": [
            "12 §"
          ],
          "heading": "Underrättelser och beslut om lönegaranti"
        },
        {
          "id": "kap-1-§-3",
          "number": 3,
          "text": "Ett beslut enligt 16, 18 eller 21 § lönegarantilagen (1992:497) ska innehålla\n   1. uppgifter enligt 2 § 1-7, där det som sägs om konkurs ska tillämpas på motsvarande sätt i fråga om företagsrekonstruktion eller annat insolvensförfarande,\n   2. skälen för beslutet, och\n   3. uppgift om hur man begär överprövning av beslutet.",
          "references": [
            "21 §",
            "2 §"
          ]
        },
        {
          "id": "kap-1-§-4",
          "number": 4,
          "text": "Om förvaltaren beslutar om ett bevakningsförfarande i en konkurs, ska förvaltaren samma dag som beslutet meddelas skicka en underrättelse om det till Skatteverket.\nFörordning (2026:332).",
          "references": [],
          "heading": "Underrättelse om ett bevakningsförfarande"
        },
        {
          "id": "kap-1-§-5",
          "number": 5,
          "text": "När en domstol har avgjort ett mål om lönegaranti ska en kopia av avgörandet skickas till Skatteverket.\n\nEn kopia av avgörandet ska även skickas till gäldenären och, i andra fall än som avses i 21 § lönegarantilagen (1992:497), till förvaltaren eller rekonstruktören.",
          "references": [
            "21 §"
          ],
          "heading": "Domstolarnas handläggning"
        },
        {
          "id": "kap-1-§-6",
          "number": 6,
          "text": "Skatteverket är utbetalande myndighet enligt lönegarantilagen (1992:497). Skatteverket ansvarar även för frågor om återbetalning enligt 34-36 §§ den lagen.",
          "references": [
            "34-36 §§"
          ],
          "heading": "Skatteverkets handläggning"
        },
        {
          "id": "kap-1-§-7",
          "number": 7,
          "text": "Skatteverket fullgör, när det gäller garantibelopp enligt lönegarantilagen (1992:497), arbetsgivarens skyldigheter i fråga om\n   1. skatteavdrag,\n   2. beslut om utmätning av lön,\n   3. kontrolluppgifter till ledning för inkomstbeskattningen, och\n   4. uppgift om betalningsmottagare i arbetsgivardeklarationer.",
          "references": []
        },
        {
          "id": "kap-1-§-8",
          "number": 8,
          "text": "Om det framgår av förvaltarens, rekonstruktörens eller Kronofogdemyndighetens underrättelse eller beslut om lönegaranti att arbetstagaren ska utföra arbete för gäldenären under uppsägningstiden, får garantibelopp för fordran på uppsägningslön betalas ut även om arbetstagaren inte har lämnat en försäkran enligt 25 § lönegarantilagen (1992:497).",
          "references": [
            "25 §"
          ]
        },
        {
          "id": "kap-1-§-9",
          "number": 9,
          "text": "Skatteverket ska på begäran lämna uppgift till Försäkringskassan om förvaltarens, rekonstruktörens eller Kronofogdemyndighetens underrättelse eller beslut om lönegaranti för uppsägningslön.\n\nSkatteverket ska till gäldenären, förvaltaren och rekonstruktören lämna besked om utbetalda, avdragna och innehållna garantibelopp.",
          "references": []
        },
        {
          "id": "kap-1-§-10",
          "number": 10,
          "text": "Om uppgifter har lämnats till en förvaltare eller en rekonstruktör enligt 23 b § lönegarantilagen (1992:497) ska Skatteverket underrätta Kronofogdemyndigheten om att sådana uppgifter har lämnats.",
          "references": [
            "23 b §"
          ]
        },
        {
          "id": "kap-1-§-11",
          "number": 11,
          "text": "Om statens fordran på grund av ett utbetalat garantibelopp inte betalas inom den tid som Skatteverket bestämmer, ska Skatteverket begära indrivning av fordran. Indrivning behöver dock inte begäras för en fordran som understiger 100 kronor, om indrivning inte krävs från allmän synpunkt.\n\nBestämmelser om indrivning finns i lagen (1993:891) om indrivning av statliga fordringar m.m. och i indrivningsförordningen (1993:1229).\n\nVid indrivning får verkställighet ske enligt utsökningsbalken.",
          "references": []
        },
        {
          "id": "kap-1-§-12",
          "number": 12,
          "text": "Utdelning i konkurs som tillfaller staten enligt 28 § lönegarantilagen (1992:497) ska betalas till Skatteverket.",
          "references": [
            "28 §"
          ],
          "heading": "Utdelning i konkurs som tillfaller staten"
        },
        {
          "id": "kap-1-§-13",
          "number": 13,
          "text": "Skatteverket får meddela föreskrifter om verkställigheten av denna förordning, utom i fråga om domstolarnas handläggning.",
          "references": [],
          "heading": "Bemyndigande"
        }
      ]
    }
  ],
  "transitional": [
    {
      "sfs": "2024:1329",
      "text": "1. Denna förordning träder i kraft den 1 februari 2025.\n   2. Genom förordningen upphävs lönegarantiförordningen (1992:501).\n   3. Med undantag för 9 a § gäller den upphävda förordningen dock fortfarande för fordringar hos en arbetsgivare som före ikraftträdandet har försatts i konkurs eller blivit föremål för något annat insolvensförfarande som avses i 1 § lönegarantilagen (1992:497)."
    },
    {
      "sfs": "2026:332",
      "text": "1. Denna förordning träder i kraft den 1 juli 2026.\n   2. I en konkurs som har beslutats före den 1 februari 2025 ska förvaltaren skicka en underrättelse enligt 4 § till Skatteverket och den länsstyrelse som anges i 5 § i den upphävda lönegarantiförordningen (1992:501)."
    }
  ]
};
