// Lönegarantilag (1992:497)
// Generated by backend/build_laws_from_docx.py from the official DOCX (Regeringskansliet fulltext).
// Versions in force on 2026-10-07. Do not edit by hand - fix the parser or the source DOCX and regenerate.
// Last amended: t.o.m. SFS 2025:800

import { LegalText } from '../legalTexts';

export const lönegaranti: LegalText = {
  "id": "sfs-1992-497",
  "title": "Lönegarantilag (1992:497)",
  "sfsNumber": "1992:497",
  "department": "Arbetsmarknadsdepartementet ARM",
  "issued": "1992-06-04",
  "lastAmended": "t.o.m. SFS 2025:800",
  "chaptered": false,
  "chapters": [
    {
      "id": "kap-1",
      "number": 1,
      "title": "Lönegarantilag (1992:497)",
      "sections": [
        {
          "id": "kap-1-§-1",
          "number": 1,
          "text": "Staten svarar enligt denna lag för betalning av arbetstagares fordran (statlig lönegaranti) hos en arbetsgivare som\n   1. har försatts i konkurs i Sverige eller i ett annat nordiskt land,\n   2. genomgår företagsrekonstruktion, eller\n   3. i ett annat land i Europeiska unionen (EU-land) eller inom Europeiska ekonomiska samarbetsområdet (EES-land) än Sverige är föremål för ett sådant insolvensförfarande som avses i artikel 2.1 i Europaparlamentets och rådets direktiv 2008/94/EG av den 22 oktober 2008 om skydd för arbetstagare vid arbetsgivarens insolvens, i lydelsen enligt Europaparlamentets och rådets direktiv (EU) 2015/1794.\nLag (2022:983).",
          "references": [],
          "heading": "Inledande bestämmelser"
        },
        {
          "id": "kap-1-§-2",
          "number": 2,
          "text": "Om konkursen har inträffat i ett annat nordiskt land, lämnas betalning enligt garantin endast för en sådan fordran som avser anställning med övervägande anknytning till Sverige eller svenska förhållanden. Lag (1997:204).",
          "references": []
        },
        {
          "id": "kap-1-§-2a",
          "number": 2,
          "text": "I fall som avses i 1 § 3 lämnas betalning enligt garantin endast om arbetstagaren för arbetsgivarens räkning utför eller utförde sitt arbete främst i Sverige.\n\nOm arbetsgivaren har försatts i konkurs i Sverige och arbetstagaren utför eller utförde sitt arbete för arbetsgivarens räkning främst i ett annat EU- eller EES-land lämnas inte betalning enligt garantin. Lag (2005:681).",
          "references": [
            "1 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-3",
          "number": 3,
          "text": "Om arbetsgivaren tidigare har varit försatt i konkurs, betalas inte fordringar som har gjorts eller hade kunnat göras gällande i den konkursen.",
          "references": []
        },
        {
          "id": "kap-1-§-3a",
          "number": 3,
          "text": "Vad som i denna lag sägs om konkurs gäller i tillämpliga delar när en arbetsgivare är föremål för ett sådant insolvensförfarande som avses i 1 § 3. Lag (2005:681).",
          "references": [
            "1 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-4",
          "number": 4,
          "text": "Vad som sägs om arbetstagare gäller även en sådan anhörig till arbetstagare som med anledning av arbetstagarens anställning har pensionsfordran hos konkursgäldenären eller gäldenären vid företagsrekonstruktion. Lag (2005:273).",
          "references": []
        },
        {
          "id": "kap-1-§-5",
          "number": 5,
          "text": "Om en fordran har överlåtits, har förvärvaren rätt till utbetalning enligt garantin (garantibelopp) endast om förvärvet har avsett mätningsarvode eller därmed jämförlig avgift eller facklig medlemsavgift.\n\nRätt till garantibelopp föreligger också om förvärvet har skett efter att konkursbeslutet eller beslutet om företagsrekonstruktion meddelades och förvärvaren är en arbetstagarorganisation i vilken överlåtaren är medlem eller en fond i vars förvaltning organisationen deltar. Lag (2005:273).",
          "references": []
        },
        {
          "id": "kap-1-§-6",
          "number": 6,
          "text": "Den som är berättigad till underhåll har rätt till garantibelopp för underhållsbidrag som har innehållits genom utmätning av lön. Försäkringskassan har inte rätt till garantibelopp för underhållsstöd som har lämnats enligt socialförsäkringsbalken. Lag (2010:1253).",
          "references": []
        },
        {
          "id": "kap-1-§-6a",
          "number": 6,
          "text": "Den myndighet som regeringen bestämmer betalar ut garantibelopp (utbetalande myndighet). Lag (2019:530).",
          "references": [],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-7",
          "number": 7,
          "text": "Vid konkurs lämnas betalning enligt garantin för sådan fordran på lön eller annan ersättning och på pension som har förmånsrätt enligt 12 eller 13 § förmånsrättslagen (1970:979).\n\nVid företagsrekonstruktion lämnas betalning enligt garantin för fordran på lön eller annan ersättning och på pension som skulle haft förmånsrätt enligt 12 eller 13 § förmånsrättslagen om arbetsgivaren i stället hade försatts i konkurs.\nLag (2005:273).",
          "references": [
            "13 §"
          ],
          "heading": "Garantins omfattning"
        },
        {
          "id": "kap-1-§-7a",
          "number": 7,
          "text": "Betalning enligt garantin lämnas också för fordran på uppsägningslön för tid efter en månad från konkursbeslutet.\nDetsamma gäller vid beslut om företagsrekonstruktion, i den mån arbetstagaren under uppsägningstiden inte utfört och inte heller borde ha utfört arbete för arbetsgivarens räkning.\n\nFordran på uppsägningslön omfattas av garantin längst för uppsägningstid som beräknats enligt 11 § lagen (1982:80) om anställningsskydd. Uppsägningslön för tid under vilken arbetstagaren inte utför arbete för annan och inte heller driver egen rörelse omfattas av garantin endast om arbetstagaren kan visa att han eller hon har anmält sig som arbetssökande hos den offentliga arbetsförmedlingen. För uppsägningstid omfattar garantin endast lön eller ersättning som överstiger inkomst vilken arbetstagaren under den tid lönen eller ersättningen avser har haft av egen rörelse eller har förvärvat eller borde ha kunnat förvärva i en annan anställning. Vid bestämmande av i vilken utsträckning fordran på lön eller ersättning under uppsägningstid omfattas av garantin skall med samtidig inkomst i annan anställning jämställas aktivitetsstöd som lämnas till den som deltar i ett arbetsmarknadspolitiskt program, i den mån stödet avser samma tid som lönen eller ersättningen och arbetstagaren har blivit berättigad till stödet efter uppsägningen.\n\nBetalning enligt garantin lämnas dock inte till sådan arbetstagare som avses i 12 § sjätte stycket förmånsrättslagen (1970:979). Lag (2005:273).",
          "references": [
            "11 §",
            "12 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-7b",
          "number": 7,
          "text": "Betalning enligt garantin lämnas inte vid konkurs eller företagsrekonstruktion för sådan del av fordran på lön eller pension som enligt 5 kap. 2 § konkurslagen (1987:672) inte får göras gällande i konkurs. Lag (2005:273).",
          "references": [
            "5 kap. 2 §"
          ],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-8",
          "number": 8,
          "text": "Om någon på grund av en fordran som omfattas av garantin har ansökt om att gäldenären ska försättas i konkurs, lämnas betalning även för kostnaden för det. Lag (2025:800).",
          "references": []
        },
        {
          "id": "kap-1-§-9",
          "number": 9,
          "text": "För sådan fordran som är förenad med förmånsrätt enligt 12 § förmånsrättslagen (1970:979) och för fordran enligt 7 a § denna lag lämnas betalning enligt garantin vid konkurs eller företagsrekonstruktion för varje arbetstagare med ett belopp som motsvarar högst fyra gånger det prisbasbelopp enligt 2 kap. 6 och 7 §§ socialförsäkringsbalken som gäller när ett beslut om konkurs eller företagsrekonstruktion fattas.\n\nFör fordran på lön eller annan ersättning gäller garantin för en sammanlagd anställningstid om högst åtta månader.\n\nFordran på ersättning för särskilda kostnader betalas före annan fordran. Lag (2010:1253).",
          "references": [
            "12 §",
            "7 a §",
            "2 kap. 6 och 7 §§"
          ]
        },
        {
          "id": "kap-1-§-9a",
          "number": 9,
          "text": "har upphävts genom lag (1997:204).",
          "references": [],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-9b",
          "number": 9,
          "text": "En lönefordran ersätts inte om det finns grundad anledning att anta att en av förutsättningarna för den anställning eller det anställningsvillkor på vilket fordran grundar sig har varit att den skulle betalas helt eller delvis genom lönegarantin. Lag (1994:636).",
          "references": [],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-10",
          "number": 10,
          "text": "Om en arbetstagare har inkomster från en annan anställning under uppsägningstiden och dessa avser samma tid som arbetstagarens fordran i konkursen eller mot gäldenären vid företagsrekonstruktion, skall han eller hon upplysa förvaltaren eller rekonstruktören om inkomsterna. I fall som avses i 21 § skall upplysningen i stället lämnas till tillsynsmyndigheten.\n\nSådan upplysning skall också lämnas om arbetstagaren får aktivitetsstöd vid deltagande i ett arbetsmarknadspolitiskt program. Lag (2005:681).",
          "references": [
            "21 §"
          ],
          "heading": "Arbetstagarens upplysningsskyldighet"
        },
        {
          "id": "kap-1-§-11",
          "number": 11,
          "text": "Om bevakning förekommer i konkursen, ska förvaltaren snarast underrätta den utbetalande myndigheten om sådana fordringar som omfattas av garantin och som enligt förvaltarens bedömning är klara.\n\nUnderrättelse om övriga fordringar som omfattas av garantin ska lämnas utan dröjsmål sedan fordringarna har blivit utdelningsgilla. Lag (2019:530).",
          "references": [],
          "heading": "Konkurs med bevakning"
        },
        {
          "id": "kap-1-§-12",
          "number": 12,
          "text": "Om förvaltaren, efter att ha lämnat en underrättelse enligt 11 § första stycket, får upplysningar enligt 10 eller 23 b § eller på annat sätt får kännedom om något förhållande som påverkar frågan till vilken del arbetstagarens fordran omfattas av förmånsrätt, ska förvaltaren snarast underrätta den utbetalande myndigheten. Lag (2024:1327).",
          "references": [
            "11 §",
            "23 b §"
          ]
        },
        {
          "id": "kap-1-§-13",
          "number": 13,
          "text": "Underrättelse enligt 11 § behöver inte lämnas om medel har betalats ut i förskott till arbetstagaren enligt 11 kap. 14 § konkurslagen (1987:672), beträffande fordran på lön för uppsägningstid senast på fordringens förfallodag och beträffande annan fordran utan dröjsmål sedan den har blivit utdelningsgill.",
          "references": [
            "11 §",
            "11 kap. 14 §"
          ]
        },
        {
          "id": "kap-1-§-14",
          "number": 14,
          "text": "Den förvaltare som efter att ha lämnat en underrättelse enligt 11 § avser att göra en förskottsbetalning till arbetstagaren enligt 13 §, ska underrätta den utbetalande myndigheten innan betalningen görs. Lag (2019:530).",
          "references": [
            "11 §",
            "13 §"
          ]
        },
        {
          "id": "kap-1-§-15",
          "number": 15,
          "text": "Förvaltaren ska för arbetstagarens räkning bevaka fordringar som enligt förvaltarens bedömning är klara.\n\nSom bevakning får förvaltaren använda en sådan underrättelse som han eller hon har lämnat till den utbetalande myndigheten enligt 11 §.\n\nFörvaltaren ska genast underrätta arbetstagaren om bevakningen. Lag (2025:800).",
          "references": [
            "11 §"
          ]
        },
        {
          "id": "kap-1-§-16",
          "number": 16,
          "text": "Vid konkurs där bevakning inte förekommer och vid företagsrekonstruktion, skall förvaltaren eller rekonstruktören snarast pröva och meddela beslut i frågan om en fordran skall betalas enligt garantin. Lag (2005:273).",
          "references": [],
          "heading": "Konkurs utan bevakning och företagsrekonstruktion"
        },
        {
          "id": "kap-1-§-17",
          "number": 17,
          "text": "Om förvaltaren eller rekonstruktören finner att fordran ska betalas enligt garantin, ska han eller hon samma dag som beslutet meddelas sända en underrättelse om beslutets innehåll till den utbetalande myndigheten. Lag (2019:530).",
          "references": []
        },
        {
          "id": "kap-1-§-18",
          "number": 18,
          "text": "Om förvaltaren eller rekonstruktören, efter att ha fattat beslut om betalning enligt garantin, får upplysningar enligt 10 eller 23 b § eller på annat sätt får kännedom om något förhållande som påverkar frågan till vilken del arbetstagarens fordran omfattas av rätt till betalning enligt garantin, ska förvaltaren eller rekonstruktören snarast ompröva sitt beslut om garantibelopp som ännu inte har betalats ut.\n\nOm omprövningen medför att utbetalning enligt garantin ska ske med ett annat belopp än tidigare, ska förvaltaren eller rekonstruktören samma dag sända en underrättelse om beslutets innehåll till den utbetalande myndigheten. Lag (2024:1327).",
          "references": [
            "23 b §"
          ]
        },
        {
          "id": "kap-1-§-19",
          "number": 19,
          "text": "Kopia av ett beslut enligt 16 eller 18 § skall samma dag som beslutet meddelades sändas till arbetstagaren och den myndighet som har tillsyn över förvaltningen i konkurser.\nLag (2006:711).",
          "references": [
            "18 §"
          ]
        },
        {
          "id": "kap-1-§-20",
          "number": 20,
          "text": "Förvaltaren och rekonstruktören får rätta beslut som innehåller en uppenbar oriktighet till följd av skrivfel, räknefel eller liknande förbiseende. Lag (2005:273).",
          "references": []
        },
        {
          "id": "kap-1-§-20a",
          "number": 20,
          "text": "Vid företagsrekonstruktion skall rekonstruktören, på begäran av den myndighet som avses i 19 §, lämna sådana uppgifter om fordringar hos gäldenären som kan ha betydelse för betalning enligt garantin. Lag (2006:711).",
          "references": [
            "19 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-21",
          "number": 21,
          "text": "Om en arbetstagare begär betalning enligt garantin för en fordran som han eller hon har mot en arbetsgivare som har försatts i konkurs i ett annat nordiskt land eller som i ett annat EU- eller EES-land än Sverige är föremål för ett sådant insolvensförfarande som avses i 1 § 3, skall arbetstagaren ansöka om utbetalning av garantibelopp hos den myndighet som avses i 19 §.\n\nStatens talan förs av den myndighet som avses i 19 §.\nLag (2006:711).",
          "references": [
            "1 §",
            "19 §"
          ],
          "heading": "Lönegaranti vid gränsöverskridande situationer"
        },
        {
          "id": "kap-1-§-21a",
          "number": 21,
          "text": "Om en arbetstagare begär betalning enligt garantin för en fordran som han eller hon har mot en arbetsgivare som i ett annat EU- eller EES-land än Sverige är föremål för ett sådant insolvensförfarande som avses i 1 § 3, skall tillsynsmyndigheten begära information om arbetstagarens utestående fordringar hos den behöriga garantiinstitutionen i det landet.\n\nOm en arbetsgivare som har försatts i konkurs i Sverige har arbetstagare i ett annat EU- eller EES-land, skall tillsynsmyndigheten lämna relevant information om fordringarna vid förfrågan från den behöriga garantiinstitutionen i det landet.\n\nRegeringen eller den myndighet regeringen bestämmer meddelar närmare föreskrifter om utbyte av information mellan tillsynsmyndigheten och behöriga garantiinstitutioner i andra länder. Lag (2005:681).",
          "references": [
            "1 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-21b",
          "number": 21,
          "text": "Det som sägs i 18 § om omprövning ska även gälla för tillsynsmyndigheten i fråga om beslut enligt 21 §.\nLag (2024:1327).",
          "references": [
            "18 §",
            "21 §"
          ],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-22",
          "number": 22,
          "text": "Har upphävts genom lag (2019:530).",
          "references": [],
          "heading": "Utbetalning av garantibelopp"
        },
        {
          "id": "kap-1-§-23",
          "number": 23,
          "text": "Garantibelopp får inte betalas ut innan arbetstagarens fordran har förfallit till betalning.\n\nÅberopas motfordran hos arbetstagaren, får ett garantibelopp, som motsvarar en sådan del av motfordran med vilken kvittning kan ske enligt lagen (1970:215) om arbetsgivares kvittningsrätt, betalas ut först om det framgår att det inte finns någon motfordran.",
          "references": []
        },
        {
          "id": "kap-1-§-23a",
          "number": 23,
          "text": "Innan ett garantibelopp betalas ut ska den utbetalande myndigheten skyndsamt kontrollera ett beslut eller en underrättelse om lönegaranti från en förvaltare, en rekonstruktör eller tillsynsmyndigheten i syfte att motverka felaktiga utbetalningar. Kontrollen ska göras mot sådana uppgifter i Skatteverkets beskattningsdatabas som avses i 2 kap. 3 § första stycket 1-5, 7, 8 och 11 lagen (2001:181) om behandling av uppgifter i Skatteverkets beskattningsverksamhet och mot andra uppgifter som förekommer i den utbetalande myndighetens lönegarantiverksamhet.\n\nEn sådan kontroll ska även göras efter det att ett garantibelopp har betalats ut, om det finns skäl för det.\nLag (2024:1327).",
          "references": [
            "2 kap. 3 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-23b",
          "number": 23,
          "text": "Uppgifter som förekommer i den utbetalande myndighetens lönegarantiverksamhet och som kan antas ha särskild betydelse för en underrättelse enligt 12 § eller en omprövning av beslut enligt 18 § ska skyndsamt lämnas till förvaltaren, rekonstruktören eller tillsynsmyndigheten.\n\nEn uppgift som omfattas av sekretess ska inte lämnas ut om övervägande skäl talar för att det intresse som sekretessen ska skydda har företräde framför intresset av att uppgiften lämnas ut.\n\nOm uppgifter har lämnats ut får ett garantibelopp inte betalas ut innan förvaltaren, rekonstruktören eller tillsynsmyndigheten har omprövat sitt tidigare ställningstagande om lönegaranti eller underrättat den utbetalande myndigheten om att uppgifterna inte ger anledning till en ny bedömning. Lag (2024:1327).",
          "references": [
            "12 §",
            "18 §"
          ],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-24",
          "number": 24,
          "text": "Innan garantibelopp betalas ut ska den utbetalande myndigheten verkställa skatteavdrag samt avdrag med belopp som ska innehållas på grund av beslut om utmätning av lön. Dessutom ska avräkning göras för förskottsbetalning som har skett enligt 11 kap. 14 § konkurslagen (1987:672) och som avser fordringar som omfattas av garantin. Lag (2019:530).",
          "references": [
            "11 kap. 14 §"
          ]
        },
        {
          "id": "kap-1-§-25",
          "number": 25,
          "text": "Innan garantibelopp för fordran på uppsägningslön betalas ut ska arbetstagaren till den utbetalande myndigheten lämna en försäkran på heder och samvete om sina anställnings- och avlöningsförhållanden under uppsägningstiden.\n\nOm arbetstagaren under uppsägningstiden inte utför arbete för konkursgäldenären, gäldenären vid företagsrekonstruktion eller någon annan och inte heller driver egen rörelse, får garantibelopp för fordran på uppsägningslön betalas ut endast om arbetstagaren visar att han eller hon för den tid fordran avser har varit anmäld som arbetssökande hos den offentliga arbetsförmedlingen. Lag (2019:530).",
          "references": []
        },
        {
          "id": "kap-1-§-26",
          "number": 26,
          "text": "Om den utbetalande myndigheten anser att uppgifterna som arbetstagaren har lämnat i en försäkran enligt 25 § kan påverka frågan till vilken del arbetstagarens fordran på uppsägningslön omfattas av rätt till betalning enligt garantin, ska den utbetalande myndigheten skyndsamt sända en kopia av försäkran till förvaltaren, rekonstruktören eller tillsynsmyndigheten.\n\nI sådana fall får garantibelopp för fordran på uppsägningslön inte betalas ut innan förvaltaren, rekonstruktören eller tillsynsmyndigheten har omprövat sitt tidigare ställningstagande om lönegaranti eller underrättat den utbetalande myndigheten om att uppgifterna i försäkran inte ger anledning till en ny bedömning. Lag (2024:1327).",
          "references": [
            "25 §"
          ]
        },
        {
          "id": "kap-1-§-27",
          "number": 27,
          "text": "Om det, sedan förvaltaren har meddelat beslut i en lönegarantifråga, förordnas att bevakning skall äga rum i konkursen, får garantibelopp inte betalas ut på grund av beslutet. Om betalningen redan har verkställts, skall den räknas av från det belopp som arbetstagaren senare visar sig ha rätt till.",
          "references": []
        },
        {
          "id": "kap-1-§-28",
          "number": 28,
          "text": "I fråga om utbetalat garantibelopp inträder staten i arbetstagarens rätt mot konkursgäldenären eller gäldenären vid företagsrekonstruktion. Staten inträder dock inte i arbetstagarens rätt enligt 12 eller 13 § förmånsrättslagen (1970:979).\n\nUtdelning i konkurs för arbetstagarens fordran som ersatts av garantin tillfaller staten upp till detta belopp.\nLag (2008:995).",
          "references": [
            "13 §"
          ]
        },
        {
          "id": "kap-1-§-29",
          "number": 29,
          "text": "Om en arbetstagare är missnöjd med förvaltarens eller rekonstruktörens beslut enligt 16 eller 18 §, får arbetstagaren väcka talan mot staten inom tre veckor från det att han eller hon fick del av beslutet.\n\nStatens talan förs av den myndighet som avses i 19 §.\nLag (2006:711).",
          "references": [
            "18 §",
            "19 §"
          ],
          "heading": "Överprövning av beslut"
        },
        {
          "id": "kap-1-§-30",
          "number": 30,
          "text": "Om den myndighet som avses i 29 § andra stycket finner att förvaltarens eller rekonstruktörens beslut är oriktigt, får myndigheten väcka talan mot arbetstagaren inom tre veckor från det att myndigheten fick del av beslutet. Lag (2005:273).",
          "references": [
            "29 §"
          ]
        },
        {
          "id": "kap-1-§-31",
          "number": 31,
          "text": "Vad som har sagts i fråga om arbetstagare i 29 och 30 §§ gäller även den som en fordran har överlåtits till enligt 5 eller 6 §.",
          "references": [
            "29 och 30 §§",
            "6 §"
          ]
        },
        {
          "id": "kap-1-§-32",
          "number": 32,
          "text": "Talan enligt 29 eller 30 § skall väckas vid den tingsrätt som handlägger konkursärendet eller ärendet om företagsrekonstruktion.\n\nEn arbetstagare, som är missnöjd med tillsynsmyndighetens beslut enligt 21 §, får inom den tid som anges i 29 § väcka talan mot staten vid den tingsrätt där arbetstagaren skall svara i tvistemål i allmänhet. Lag (2005:273).",
          "references": [
            "30 §",
            "21 §",
            "29 §"
          ]
        },
        {
          "id": "kap-1-§-33",
          "number": 33,
          "text": "I mål enligt 29 och 30 §§ får det beslutas att vardera parten skall bära sin rättegångskostnad, även om arbetstagaren har förlorat målet.",
          "references": [
            "29 och 30 §§"
          ]
        },
        {
          "id": "kap-1-§-34",
          "number": 34,
          "text": "Om någon genom oriktiga uppgifter eller på annat sätt har orsakat att garantibelopp har betalats ut obehörigt eller med för högt belopp, skall återbetalning ske av vad som har betalats för mycket.\n\nSådan återbetalning skall ske också om någon i annat fall har tagit emot garantibelopp obehörigt eller med för högt belopp och skäligen hade bort inse detta.",
          "references": [],
          "heading": "Återbetalning av garantibelopp"
        },
        {
          "id": "kap-1-§-35",
          "number": 35,
          "text": "Om betalning enligt garantin har skett och konkursbeslutet eller beslutet om företagsrekonstruktion därefter upphävs genom ett beslut som vinner laga kraft, skall den som tagit emot betalningen betala tillbaka beloppet. Lag (2005:273).",
          "references": []
        },
        {
          "id": "kap-1-§-36",
          "number": 36,
          "text": "Om det finns särskilda skäl, får återbetalningsskyldighet enligt 34 och 35 §§ efterskänkas helt eller delvis.",
          "references": [
            "34 och 35 §§"
          ]
        },
        {
          "id": "kap-1-§-37",
          "number": 37,
          "text": "Den utbetalande myndigheten får behandla personuppgifter om det behövs för kontroll och utbetalning av garantibelopp och för att i övrigt utföra sina uppgifter i lönegarantiverksamheten.\n\nPersonuppgifter som behandlas enligt första stycket får också behandlas om det behövs för att fullgöra uppgiftslämnande som sker i överensstämmelse med lag eller förordning.\nLag (2024:1327).",
          "references": [],
          "heading": "Behandling av personuppgifter"
        },
        {
          "id": "kap-1-§-38",
          "number": 38,
          "text": "Rätten att göra invändningar enligt artikel 21.1 i Europaparlamentets och rådets förordning (EU) 2016/679 av den 27 april 2016 om skydd för fysiska personer med avseende på behandling av personuppgifter och om det fria flödet av sådana uppgifter och om upphävande av direktiv 95/46/EG (allmän dataskyddsförordning) gäller inte vid sådan behandling av personuppgifter i den utbetalande myndighetens lönegarantiverksamhet som är tillåten enligt denna lag eller föreskrifter som har meddelats i anslutning till lagen.\nLag (2024:1327).",
          "references": []
        }
      ]
    }
  ],
  "transitional": [
    {
      "sfs": "1992:497",
      "text": "1. Denna lag träder i kraft den 1 juli 1992, då lagen (1970:741) om statlig lönegaranti vid konkurs skall upphöra att gälla.\n   2. Äldre föreskrifter gäller fortfarande för fordran hos en arbetsgivare som har försatts i konkurs före ikraftträdandet."
    },
    {
      "sfs": "1994:636",
      "text": "1. Denna lag träder i kraft den 1 juli 1994.\n   2. Den äldre bestämmelsen i 25 § om utbetalning av garantibelopp skall fortfarande gälla i fråga om fordringar mot arbetsgivare som har försatts i konkurs före ikraftträdandet."
    },
    {
      "sfs": "2003:544",
      "text": "1. Denna lag träder i kraft den 1 januari 2004.\n   2. I fråga om en konkurs som har beslutats på grund av en ansökan som gjorts före ikraftträdandet tillämpas äldre bestämmelser."
    },
    {
      "sfs": "2005:273",
      "text": "1. Denna lag träder i kraft den 1 juni 2005.\n   2. De nya bestämmelserna om lönegaranti vid företagsrekonstruktion skall tillämpas om beslutet om företagsrekonstruktion fattas på grund av en ansökan om företagsrekonstruktion som inkommit till tingsrätten den 1 juni 2005 eller senare."
    },
    {
      "sfs": "2005:681",
      "text": "Denna lag träder i kraft den 7 oktober 2005 och tillämpas i fråga om insolvensförfaranden som inletts därefter."
    },
    {
      "sfs": "2008:995",
      "text": "1. Denna lag träder i kraft den 1 januari 2009.\n   2. I en konkurs eller företagsrekonstruktion som har beslutats på grund av en ansökan som har inkommit till domstolen före ikraftträdandet tillämpas äldre bestämmelser."
    },
    {
      "sfs": "2024:1327",
      "text": "1. Denna lag träder i kraft den 1 februari 2025.\n   2. Äldre föreskrifter gäller fortfarande för fordringar hos en arbetsgivare som före ikraftträdandet har försatts i konkurs eller blivit föremål för något annat insolvensförfarande som avses i 1 §."
    },
    {
      "sfs": "2025:800",
      "text": "1. Denna lag träder i kraft den 1 juli 2026.\n   2. Den äldre lydelsen av 8 § gäller för en konkurs som har beslutats före ikraftträdandet."
    }
  ]
};
