// Semesterlag (1977:480)
// Generated by backend/build_laws_from_docx.py from the official DOCX (Regeringskansliet fulltext).
// Versions in force on 2026-10-07. Do not edit by hand - fix the parser or the source DOCX and regenerate.
// Last amended: t.o.m. SFS 2014:424

import { LegalText } from '../legalTexts';

export const semesterlag: LegalText = {
  "id": "sfs-1977-480",
  "title": "Semesterlag (1977:480)",
  "sfsNumber": "1977:480",
  "department": "Arbetsmarknadsdepartementet ARM",
  "issued": "1977-06-09",
  "lastAmended": "t.o.m. SFS 2014:424",
  "chaptered": false,
  "chapters": [
    {
      "id": "kap-1",
      "number": 1,
      "title": "Semesterlag (1977:480)",
      "sections": [
        {
          "id": "kap-1-§-1",
          "number": 1,
          "text": "Arbetstagare har rätt till semesterförmåner enligt denna lag. Semesterförmånerna utgörs av semesterledighet, semesterlön och semesterersättning.\n\nSärskilda bestämmelser för vissa arbetstagare finns i\n   1. lagen (1963:115) om förlängd semester för vissa arbetstagare med radiologiskt arbete,\n   2. lagen (2010:449) om Försvarsmaktens personal vid internationella militära insatser, och\n   3. lagen (2012:332) om vissa försvarsmaktsanställningar.\nLag (2012:333).",
          "references": [],
          "heading": "Semesterförmåner"
        },
        {
          "id": "kap-1-§-2",
          "number": 2,
          "text": "Ett avtal, som innebär att arbetstagares rättigheter enligt denna lag inskränks, är ogiltigt i den delen. Detta gäller dock inte, om något annat framgår av lagen.\nLag (2009:1439).",
          "references": [],
          "heading": "Överenskommelser mellan arbetsgivare och arbetstagare"
        },
        {
          "id": "kap-1-§-2a",
          "number": 2,
          "text": "Genom avtal får avvikelse göras från 5, 12, 12 b, 19-21 och 30 a §§, i den utsträckning som framgår av de bestämmelserna.\n\nGenom kollektivavtal, som på arbetstagarsidan har slutits eller godkänts av en central arbetstagarorganisation, får avvikelse göras från 3, 3 a, 9, 11 § andra stycket, 16-16 b, 22, 26, 26 a, 29, 29 a och 30 §§.\n\nEn arbetsgivare, som är bunden av ett kollektivavtal som omfattar frågor som avses i första och andra styckena, får i dessa frågor tillämpa avtalet även på en arbetstagare som inte är medlem av den avtalsslutande arbetstagarorganisationen. Detta gäller under förutsättning att arbetstagaren sysselsätts i arbete som avses med avtalet och inte omfattas av något annat tillämpligt kollektivavtal.\nLag (2009:1439).",
          "references": [
            "5, 12, 12 b, 19-21 och 30 a §§",
            "3, 3 a, 9, 11 §",
            "16-16 b, 22, 26, 26 a, 29, 29 a och 30 §§"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-3",
          "number": 3,
          "text": "Med semesterår avses tiden från och med den 1 april ett år till och med den 31 mars påföljande år. Motsvarande tid närmast före ett semesterår kallas intjänandeår.\nLag (2009:1439).",
          "references": [],
          "heading": "Semesterår och intjänandeår"
        },
        {
          "id": "kap-1-§-3a",
          "number": 3,
          "text": "Semesterledighet avser hela dagar. I ledigheten ingår enstaka semesterdagar eller en period av semesterdagar, inklusive arbetsfria dagar. Ledigheten börjar och slutar med en semesterdag.\n\nLördag och söndag räknas inte som semesterdagar annat än i fall som avses i 9 § tredje stycket. Med söndag jämställs allmän helgdag samt midsommarafton, julafton och nyårsafton.\nLag (2009:1439).",
          "references": [
            "9 §"
          ],
          "suffix": "a",
          "heading": "Semesterledighet och semesterdagar"
        },
        {
          "id": "kap-1-§-4",
          "number": 4,
          "text": "En arbetstagare har rätt till tjugofem semesterdagar varje semesterår. Om anställningen påbörjas efter den 31 augusti under semesteråret, har arbetstagaren rätt till endast fem semesterdagar.\n\nUnder semesterledighet ska arbetstagaren ha semesterlön, om sådan har tjänats in enligt 7 §. Lag (2009:1439).",
          "references": [
            "7 §"
          ]
        },
        {
          "id": "kap-1-§-5",
          "number": 5,
          "text": "När det gäller en anställning som avses pågå i högst tre månader och som inte varar längre tid, får det avtalas att semesterledighet inte ska läggas ut. I sådant fall har arbetstagaren rätt till semesterersättning.\n\nArbetstagare i gymnasial lärlingsanställning har rätt till semesterledighet enbart om detta har avtalats särskilt. En arbetstagare i sådan anställning har rätt till semesterersättning för den semesterlön som tjänats in men inte tagits ut. Sådan ersättning ska, om inte annat avtalats eller följer av 28 § första och andra styckena eller 30 §, betalas ut senast en månad efter vårterminens slut.\nLag (2014:424).",
          "references": [
            "28 §",
            "30 §"
          ]
        },
        {
          "id": "kap-1-§-6",
          "number": 6,
          "text": "En arbetstagare som byter anställning har rätt till semesterledighet i den nya anställningen endast i den utsträckning arbetstagaren inte redan har haft sådan ledighet i den tidigare anställningen.\n\nOm överföring av semesterförmåner till ny anställning hos samma arbetsgivare finns bestämmelser i 30 b §.\nLag (2009:1439).",
          "references": [
            "30 b §"
          ]
        },
        {
          "id": "kap-1-§-7",
          "number": 7,
          "text": "Antalet semesterdagar med semesterlön beräknas på följande sätt. Från de dagar arbetstagaren har varit anställd hos arbetsgivaren under intjänandeåret (anställningstiden) subtraheras de dagar då arbetstagaren varit helt frånvarande från arbetet utan lön. Frånvaro som beror på semesterledighet, permittering, korttidsarbete eller ledighet som enligt 17-17 b §§ är semesterlönegrundande, liksom arbetsfria dagar som infaller under sådana frånvaroperioder, ska dock räknas in i anställningstiden. Differensen divideras med antalet dagar under intjänandeåret. Kvoten multipliceras med tjugofem. Om ett brutet tal då uppstår, avrundas detta till närmast högre hela tal. Lag (2013:950).",
          "references": [
            "17-17 b §§"
          ],
          "heading": "Semesterdagar med semesterlön"
        },
        {
          "id": "kap-1-§-8",
          "number": 8,
          "text": "En arbetstagare får avstå från rätt till semesterledighet som inte är förenad med semesterlön.\n\nEn arbetstagare ska på begäran lämna arbetsgivaren besked om sina önskemål när det gäller utläggningen av semesterledighet utan semesterlön eller i vilken omfattning arbetstagaren önskar avstå från sådan ledighet. Besked behöver inte lämnas innan arbetsgivaren har meddelat hur många semesterdagar utan lön arbetstagaren har eller kan beräknas få rätt till.\n\nHar semesterledighet utan lön lagts ut med anledning av arbetstagarens besked enligt första stycket, får arbetstagaren inte senare avstå från ledigheten utom i fall som anges i 13 §. Lag (2009:1439).",
          "references": [
            "13 §"
          ],
          "heading": "Semesterdagar utan semesterlön"
        },
        {
          "id": "kap-1-§-9",
          "number": 9,
          "text": "En arbetstagare, som regelbundet arbetar lördag eller söndag eller båda dessa dagar, har vid semesterledighet som omfattar minst fem dagar rätt till ledighet motsvarande tid av veckoslut, dels under semesterledigheten, dels antingen omedelbart före eller omedelbart efter denna. Omfattar semesterledigheten minst nitton dagar har arbetstagaren rätt till ledighet motsvarande tid av veckoslut såväl omedelbart före som omedelbart efter ledigheten, om inte särskilda skäl talar emot detta.\n\nHar i fall som avses i första stycket arbetstagaren ledighet av motsvarande omfattning en veckodag, som inte är lördag eller söndag, och som infaller under semesterledigheten, räknas den veckodagen som semesterdag.\n\nOm semesterledigheten är kortare än fem dagar och arbetstagaren är ledig en lördag eller söndag, som annars skulle ha utgjort arbetsdag, räknas sådan dag som semesterdag. Arbetsfri dag ska då inte anses som semesterdag.\nLag (2009:1439).",
          "references": [],
          "heading": "Semesterledighet för arbetstagare som regelbundet arbetar lördag eller söndag"
        },
        {
          "id": "kap-1-§-10",
          "number": 10,
          "text": "Mellan parter som träffar kollektivavtal om löner och allmänna anställningsvillkor bör det, om arbetstagarparten begär det, även träffas kollektivavtal om medbestämmanderätt för arbetstagarna i frågor som rör förläggningen av semesterledighet. I fråga om en arbetstagare för vilken ett sådant avtal inte har träffats gäller bestämmelserna i andra och tredje styckena.\n\nDet som föreskrivs om arbetsgivares förhandlingsskyldighet i 11 och 13 §§ lagen (1976:580) om medbestämmande i arbetslivet ska tillämpas på motsvarande sätt när det gäller förläggning av sådan semesterledighet som avses i 12 §. Om arbetstagaren inte företräds av en förhandlingsberättigad organisation eller om en sådan organisation inte önskar förhandla, ska arbetsgivaren samråda med arbetstagaren om ledighetens förläggning.\n\nNär det gäller förläggningen av annan semesterledighet än sådan som avses i 12 §, ska arbetsgivaren samråda med arbetstagaren, om förhandling med arbetstagarens organisation inte har ägt rum. Lag (2009:1439).",
          "references": [
            "11 och 13 §§",
            "12 §"
          ],
          "heading": "Semesterledighetens förläggning"
        },
        {
          "id": "kap-1-§-11",
          "number": 11,
          "text": "Om det inte går att komma överens om hur semesterledighet ska förläggas, bestämmer arbetsgivaren om förläggningen, om inte något annat har avtalats.\n\nHar beslut om förläggning av semesterledigheten träffats på något annat sätt än genom överenskommelse med en arbetstagare eller dennes företrädare, ska arbetsgivaren underrätta arbetstagaren om beslutet. Underrättelsen ska lämnas senast två månader före ledighetens början. Om det finns särskilda skäl, får den lämnas senare, dock om möjligt minst en månad före ledighetens början. Lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-12",
          "number": 12,
          "text": "Om inte annat har avtalats, ska semesterledigheten förläggas så, att arbetstagaren får en ledighetsperiod av minst fyra veckor under juni-augusti. Även utan stöd av avtal får en sådan semesterperiod förläggas till annan tid, när särskilda skäl föranleder det. Lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-12a",
          "number": 12,
          "text": "Semesterledighet ska förläggas så, att arbetstagare med lägre sysselsättningsgrad än heltid eller med oregelbunden arbetstid får lika lång ledighet som en arbetstagare som arbetar heltid eller en arbetstagare med regelbunden arbetstid. Lag (2009:1439).",
          "references": [],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-12b",
          "number": 12,
          "text": "Av semesterdagar som läggs ut under ett visst semesterår ska dagar med semesterlön läggas ut först, om inte annat har avtalats. Lag (2009:1439).",
          "references": [],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-13",
          "number": 13,
          "text": "Beslutar en arbetsgivare om permittering som arbetstagaren inte hade anledning att räkna med när besked lämnades enligt 8 §, har arbetstagaren rätt att avstå från utlagd semesterledighet utan semesterlön, om ledigheten sammanfaller med permitteringsperioden.\n\nHar en arbetstagare lämnat besked enligt 8 § innan han eller hon fått information om hur arbetstiden ska läggas ut vid korttidsarbete, har arbetstagaren rätt att avstå från utlagd semesterledighet utan semesterlön, om semesterledigheten sammanfaller med tid då arbetstagaren ska vara helt frånvarande på grund av korttidsarbete.\n\nFörsta och andra styckena gäller dock endast om arbetstagaren underrättar arbetsgivaren senast två veckor före semesterledighetens början. Får arbetstagaren först senare kännedom om permitteringen eller hur arbetstiden ska läggas ut vid korttidsarbete, får arbetstagaren avstå från semesterledigheten om han eller hon utan dröjsmål underrättar arbetsgivaren. Har semesterledigheten då inletts, upphör ledigheten vid utgången av den dag då arbetsgivaren underrättades. Lag (2013:950).",
          "references": [
            "8 §"
          ],
          "heading": "Semesterledighet vid permittering eller korttidsarbete"
        },
        {
          "id": "kap-1-§-14",
          "number": 14,
          "text": "Semesterledighet får inte utan arbetstagarens medgivande förläggas till uppsägningstid.\n\nSkulle vid uppsägning från arbetsgivarens sida uppsägningstiden helt eller delvis infalla under redan utlagd semesterledighet och beror uppsägningen på förhållanden som inte hänför sig till arbetstagaren personligen, ska semesterledighetens förläggning i samma mån upphävas, om arbetstagaren begär det.\n\nFörsta och andra styckena gäller inte om uppsägningstiden överstiger sex månader. Lag (2009:1439).",
          "references": [],
          "heading": "Semesterledighet i samband med uppsägning och sjukdom m.m."
        },
        {
          "id": "kap-1-§-15",
          "number": 15,
          "text": "Om det under semesterledigheten infaller en eller flera dagar då arbetstagaren inte hade kunnat arbeta på grund av sjukdom eller arbetsskada, eller en eller flera dagar som är semesterlönegrundande enligt 17 a och 17 b §§ ska, om arbetstagaren utan dröjsmål begär det, sådana dagar inte räknas som semesterdagar. I sådant fall ska de semesterdagar som återstår förläggas i ett sammanhang, om arbetstagaren inte medger annat. Lag (2011:129).",
          "references": [
            "17 a och 17 b §§"
          ]
        },
        {
          "id": "kap-1-§-16",
          "number": 16,
          "text": "Semesterlön för en arbetstagare som har lön bestämd per vecka eller månad beräknas enligt 16 a §, om inte annat framgår av andra stycket eller arbetsgivaren väljer att beräkna semesterlönen enligt 16 b §.\n\nSemesterlön beräknas enligt 16 b § för en arbetstagare som har\n   1. lön som inte är bestämd per vecka eller månad,\n   2. lön som regelbundet består av en fast och en rörlig del om den rörliga lönedelen kan uppskattas till minst tio procent av den sammanlagda lönen under semesteråret, eller\n   3. en sysselsättningsgrad som har varierat under intjänandeåret, eller som har\n   4. ändrat sysselsättningsgrad mellan intjänandeåret och semestertillfället, eller\n   5. varit frånvarande under intjänandeåret av skäl som inte är semesterlönegrundande enligt 17-17 b §§, dock inte om frånvaron pågått i samma omfattning under hela intjänandeåret och pågår i den omfattningen vid semestertillfället.\n\nSärskilda bestämmelser om vissa förmåner vid beräkning av semesterlön finns i 24 och 25 §§. Lag (2009:1439).",
          "references": [
            "16 a §",
            "16 b §",
            "17-17 b §§",
            "24 och 25 §§"
          ],
          "heading": "Beräkning av semesterlön"
        },
        {
          "id": "kap-1-§-16a",
          "number": 16,
          "text": "Semesterlön enligt sammalöneregeln är den vid semestertillfället aktuella vecko- eller månadslönen, eventuella fasta lönetillägg samt ett semestertillägg.\n\nSemestertillägget för varje betald semesterdag är för veckoavlönade arbetstagare 1,82 procent av veckolönen och för månadsavlönade arbetstagare 0,43 procent av månadslönen. Har arbetstagaren fasta lönetillägg ska vecko- respektive månadslönen ökas med dessa tillägg före beräkningen av semestertillägget.\n\nHar arbetstagaren även rörliga lönedelar är semesterlönen för dessa lönedelar tolv procent av arbetstagarens sammanlagda förfallna rörliga lön under semesteråret. Lag (2009:1439).",
          "references": [],
          "suffix": "a",
          "heading": "Semesterlön enligt sammalöneregeln"
        },
        {
          "id": "kap-1-§-16b",
          "number": 16,
          "text": "Semesterlön enligt procentregeln utgör tolv procent av arbetstagarens förfallna lön i en anställning under intjänandeåret.\n\nI lönesumman ska inte följande inräknas:\n   1. semesterlön,\n   2. ersättning för dag då arbetstagaren helt eller delvis har haft semesterlönegrundande frånvaro enligt 17-17 b §§, eller\n   3. permitteringslön som lämnas i anledning av driftsuppehåll med samtidig semester när rätt till semesterlön inte föreligger för samma tid.\n\nFör varje sådan frånvarodag som anges i andra stycket 2 ökas i stället lönesumman med ett belopp motsvarande den inkomst arbetstagaren skulle ha haft om arbete i stället utförts i normal omfattning för arbetsgivarens räkning. Med normal omfattning avses arbetstagarens ordinarie arbetstidsmått. Går beloppet inte att fastställa ska det uppskattas till den inkomst som kan antas skulle ha betalats om arbetstagaren under frånvarotiden hade arbetat för arbetsgivarens räkning.\nLag (2009:1439).",
          "references": [
            "17-17 b §§"
          ],
          "suffix": "b",
          "heading": "Semesterlön enligt procentregeln"
        },
        {
          "id": "kap-1-§-17",
          "number": 17,
          "text": "Frånvaro från arbetet är semesterlönegrundande när det gäller ledighet på grund av sjukdom, om frånvaron under intjänandeåret inte överstiger 180 dagar, eller om frånvaron beror på arbetsskada. I sådan frånvaroperiod inräknas även dagar när arbetstagaren inte skulle ha utfört arbete.\n\nFrånvaron upphör att vara semesterlönegrundande då arbetstagaren varit helt eller delvis frånvarande från arbetet under ett helt intjänandeår, utan längre avbrott i frånvaron än fjorton dagar i en följd. Lag (2009:1439).",
          "references": [],
          "heading": "Semesterlönegrundande frånvaro"
        },
        {
          "id": "kap-1-§-17a",
          "number": 17,
          "text": "Frånvaro från arbetet är semesterlönegrundande när det gäller ledighet enligt föräldraledighetslagen (1995:584) i fråga om\n   1. ledighet enligt 8 § första stycket nämnda lag, om frånvaron under intjänandeåret inte överstiger 120 dagar, eller för ensamstående förälder 180 dagar,\n   2. tid för vilken graviditetspenning utges enligt 10 kap.\nsocialförsäkringsbalken, eller\n   3. tid för vilken föräldrapenning lämnas med anledning av barns födelse eller adoption enligt 12 kap.\nsocialförsäkringsbalken, om frånvaron för varje barn eller vid flerbarnsbörd sammanlagt inte överstiger 120 dagar eller för ensamstående förälder 180 dagar.\n\nI en frånvaroperiod enligt första stycket räknas in även dagar när arbetstagaren inte skulle ha utfört arbete.\nLag (2010:1223).",
          "references": [
            "8 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-17b",
          "number": 17,
          "text": "Frånvaro från arbetet är semesterlönegrundande när det gäller\n   1. ledighet med anledning av risk för överförande av smitta,\n      a) om arbetstagaren är berättigad till smittbärarersättning enligt 46 kap. socialförsäkringsbalken, och\n      b) om frånvaron under intjänandeåret inte överstiger 180 dagar,\n   2. ledighet enligt lagen (1988:1465) om ledighet för närståendevård, om frånvaron under intjänandeåret inte överstiger 45 dagar,\n   3. ledighet för utbildning som till väsentlig del avser fackliga eller med facklig verksamhet sammanhängande frågor eller för ersättningsberättigande teckenspråksutbildning för vissa föräldrar (TUFF), om frånvaron under intjänandeåret inte överstiger 180 dagar och ledigheten inte ger rätt till semesterlön enligt någon annan lag,\n   4. ledighet på grund av grundutbildning om högst 60 dagar eller repetitionsutbildning enligt lagen (1994:1809) om totalförsvarsplikt, om frånvaron under intjänandeåret inte överstiger 60 dagar, eller\n   5. ledighet enligt lagen (1986:163) om rätt till ledighet för utbildning i svenska för invandrare.\n\nI en frånvaroperiod enligt första stycket räknas in även dagar när arbetstagaren inte skulle ha utfört arbete.\nLag (2010:1224).",
          "references": [],
          "suffix": "b"
        },
        {
          "id": "kap-1-§-18",
          "number": 18,
          "text": "En arbetstagare, som under ett semesterår har rätt till mer än tjugo semesterdagar med lön, får spara en eller flera sådana överskjutande dagar till ett senare semesterår.\n\nEn sparad semesterdag ska läggas ut inom fem år från utgången av det semesterår då den sparades, om inte annat följer av 20 § andra stycket.\n\nSemesterdagar får inte sparas under ett semesterår då arbetstagaren får ut semesterdagar, som har sparats från tidigare år. Lag (2009:1439).",
          "references": [
            "20 §"
          ],
          "heading": "Rätt att spara semesterledighet"
        },
        {
          "id": "kap-1-§-19",
          "number": 19,
          "text": "Vill en arbetstagare spara semesterdagar eller ta ut sparade semesterdagar i anslutning till semesterledigheten i övrigt, ska arbetsgivaren underrättas i samband med att förläggningen av årets semesterledighet bestäms.\nUnderrättelse behöver dock inte lämnas förrän arbetsgivaren har meddelat hur många semesterdagar med lön arbetstagaren har eller kan beräknas få rätt till. En arbetstagare som vill ta ut sparade semesterdagar utan sammanhang med semesterledigheten i övrigt, ska meddela arbetsgivaren detta senast två månader i förväg.\n\nFörsta stycket gäller endast om inte annat har avtalats.\nLag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-20",
          "number": 20,
          "text": "Sparade semesterdagar ska förläggas till det semesterår som arbetstagaren väljer. Detta gäller dock inte om något annat har avtalats eller om det finns särskilda skäl mot att semesterdagarna förläggs till det året.\n\nOm arbetstagaren har avsett att sparade semesterdagar ska förläggas till det femte året efter det semesterår då de sparades och om sådan förläggning skulle medföra betydande olägenhet, får överenskommelse träffas om att semesterdagarna ska läggas ut under det sjätte året. Lag (2009:1439).",
          "references": [],
          "heading": "Förläggning av sparade semesterdagar"
        },
        {
          "id": "kap-1-§-21",
          "number": 21,
          "text": "Önskar en arbetstagare samtidigt få ut minst fem sparade semesterdagar, ska dessa och hela semesterledigheten för semesteråret läggas ut i en följd, om inte annat har avtalats. Lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-22",
          "number": 22,
          "text": "Semesterlön för sparade semesterdagar beräknas enligt 16-16 b §§. Samtliga sparade semesterdagar som läggs ut ska betraktas som intjänade under det närmast föregående intjänandeåret. Lag (2009:1439).",
          "references": [
            "16-16 b §§"
          ],
          "heading": "Semesterlön för sparade semesterdagar"
        },
        {
          "id": "kap-1-§-23",
          "number": 23,
          "text": "Har upphävts genom lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-24",
          "number": 24,
          "text": "Vid beräkning av semesterlön ska hänsyn inte tas till förmån av fri bostad eller till en löneförmån, som är avsedd att utgöra ersättning för särskilda kostnader.\nLag (2009:1439).",
          "references": [],
          "heading": "Särskilda bestämmelser om semesterlön"
        },
        {
          "id": "kap-1-§-25",
          "number": 25,
          "text": "En arbetstagare, som får fri kost i arbetsgivarens hushåll, har rätt till skälig kostersättning för de semesterdagar då förmånen inte har utnyttjats till någon del.\nLag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-26",
          "number": 26,
          "text": "Arbetsgivaren ska betala ut semesterlön till arbetstagaren i samband med semesterledigheten.\n\nSemesterlön för rörliga lönedelar som avses i 16 a § tredje stycket ska betalas senast en månad efter semesterårets utgång. Lag (2009:1439).",
          "references": [
            "16 a §"
          ],
          "heading": "Utbetalning av semesterlön"
        },
        {
          "id": "kap-1-§-26a",
          "number": 26,
          "text": "Semesterdagar med semesterlön som inte har sparats enligt 18 § och som inte har kunnat läggas ut under semesteråret ersätts med semesterlön. Sådan semesterlön bestäms enligt grunderna för beräkning av semesterlön i 16-16 b §§, och ska betalas ut senast en månad efter semesterårets utgång. Semesterlön betalas dock ut endast för det antal dagar som tillsammans med det antal dagar som intjänats under intjänandeåret överstiger tjugofem.\nLag (2009:1439).",
          "references": [
            "18 §",
            "16-16 b §§"
          ],
          "suffix": "a",
          "heading": "Semesterlön för semester som inte har kunnat läggas ut"
        },
        {
          "id": "kap-1-§-27",
          "number": 27,
          "text": "Har upphävts genom lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-28",
          "number": 28,
          "text": "Om anställningen upphör innan arbetstagaren har fått den semesterlön som tjänats in, ska arbetstagaren i stället få semesterersättning. Detta gäller inte om annat följer av 30 b eller 31 §.\n\nMotsvarande ska gälla om arbetstagarens anställningsvillkor ändras så att semesterledighet med semesterlön ska förläggas redan under intjänandeåret. I sådant fall ska bestämmelserna om semesterersättning tillämpas som om anställningen hade upphört vid den tidpunkt från vilken de nya anställningsvillkoren ska gälla.\n\nSärskilda bestämmelser om semesterersättning finns i 5 § för\n   1. arbetstagare som anställs för arbete som avses pågå i högst tre månader, och\n   2. arbetstagare i gymnasial lärlingsanställning.\nLag (2014:424).",
          "references": [
            "31 §",
            "5 §"
          ],
          "heading": "Semesterersättning"
        },
        {
          "id": "kap-1-§-29",
          "number": 29,
          "text": "Semesterersättning bestäms enligt grunderna för beräkning av semesterlön.\n\nFör sparade semesterdagar ska semesterersättning beräknas som om de tagits ut under det semesterår då anställningen upphörde. Lag (2009:1439).",
          "references": []
        },
        {
          "id": "kap-1-§-29a",
          "number": 29,
          "text": "Har en arbetstagare mottagit semesterlön i förskott, minskas semesterersättningen med sådan semesterlön. Detta gäller dock inte, om den semesterlön som togs emot i förskott utbetalades mer än fem år före anställningens upphörande eller om anställningen har upphört på grund av\n   1. arbetstagarens sjukdom,\n   2. förhållanden som avses i 4 § tredje stycket lagen (1982:80) om anställningsskydd, eller\n   3. uppsägning från arbetsgivarens sida som beror på förhållanden som inte hänför sig till arbetstagaren personligen, utom när uppsägning sker i samband med en konkurs. Lag (2009:1439).",
          "references": [
            "4 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-30",
          "number": 30,
          "text": "Semesterersättning ska betalas ut till arbetstagaren utan oskäligt dröjsmål och senast en månad efter anställningens upphörande.\n\nOm det inte går att beräkna semesterersättning inom en månad efter anställningens upphörande, ska den betalas ut inom en vecka efter det att hindret mot att beräkna ersättningen upphörde. Lag (2009:1439).",
          "references": [],
          "heading": "Utbetalning av semesterersättning"
        },
        {
          "id": "kap-1-§-30a",
          "number": 30,
          "text": "Om en arbetstagare utför arbete under sådana förhållanden att det inte kan anses vara arbetsgivarens uppgift att vaka över hur arbetet är ordnat, får avtal träffas om avvikelse från bestämmelserna om förläggning av semesterledighet i 9-15 §§. Sådan avvikelse får inte innebära en inskränkning i arbetstagarens rätt att ta ut tjugofem semesterdagar, eller det mindre antal semesterdagar som arbetstagaren har rätt till varje semesterår.\nLag (2009:1439).",
          "references": [
            "9-15 §§"
          ],
          "suffix": "a",
          "heading": "Okontrollerade arbetstagare"
        },
        {
          "id": "kap-1-§-30b",
          "number": 30,
          "text": "Om det innan en anställning har upphört står klart att en ny anställning mellan parterna kommer att påbörjas i nära anslutning till den tidigare, ska anställningarna i semesterhänseende räknas som en enda anställning.\n\nFörsta stycket tillämpas endast om\n   1. den intjänade semesterledigheten inte redan har lagts ut,\n   2. semesterersättning inte redan har betalats ut, och\n   3. arbetstagaren har förklarat att intjänade semesterförmåner ska överföras till den nya anställningen. Lag (2009:1439).",
          "references": [],
          "suffix": "b",
          "heading": "Ny anställning i anslutning till en tidigare anställning"
        },
        {
          "id": "kap-1-§-31",
          "number": 31,
          "text": "En arbetstagares rätt enligt denna lag påverkas inte av att ett företag, en verksamhet eller en del av en verksamhet, övergår till en ny arbetsgivare genom en sådan övergång som omfattas av 6 b § lagen (1982:80) om anställningsskydd.\nArbetstagarens rätt påverkas inte heller av att ett företag eller en del av ett företag övergår till en ny arbetsgivare i samband med konkurs.\n\nÖvergår en arbetstagare till en ny arbetsgivare inom samma koncern, ska arbetstagaren i semesterhänseende ha samma rätt i den nya anställningen som i den tidigare. Detta förutsätter dock, att arbetstagaren inte får semesterersättning av den tidigare arbetsgivaren och att arbetstagaren senast en månad efter anställningens upphörande förklarar för både den tidigare och den nye arbetsgivaren, att han eller hon vill överföra intjänade semesterförmåner till den nya anställningen.\n\nI fall som avses i andra stycket är den nye arbetsgivaren berättigad att av den tidigare arbetsgivaren få ett belopp motsvarande den semesterersättning som den tidigare arbetsgivaren annars skulle ha betalat till arbetstagaren.\nLag (2009:1439).",
          "references": [
            "6 b §"
          ],
          "heading": "Övergång till ny arbetsgivare"
        },
        {
          "id": "kap-1-§-32",
          "number": 32,
          "text": "Arbetsgivare som bryter mot denna lag skall till arbetstagaren utge, förutom den semesterlön eller semesterersättning vartill arbetstagaren kan vara berättigad, ersättning för uppkommen skada.\n\nVid bedömande om och i vad mån skada har uppstått skall hänsyn tagas även till arbetstagarens intresse av att erhålla semesterledighet och till övriga omständigheter av annan än rent ekonomisk betydelse.\n\nOm det med hänsyn till skadans storlek eller andra omständigheter är skäligt, kan skadeståndet nedsättas eller helt bortfalla.",
          "references": [],
          "heading": "Skadestånd"
        },
        {
          "id": "kap-1-§-33",
          "number": 33,
          "text": "En arbetstagare som vill begära semesterlön, semesterersättning eller skadestånd enligt denna lag ska väcka talan inom två år från utgången av det semesterår då arbetstagaren enligt lagen skulle ha fått den förmån som begäran gäller. Försummar arbetstagaren det, är rätten till talan förlorad. Lag (2009:1439).",
          "references": [],
          "heading": "Preskription"
        },
        {
          "id": "kap-1-§-34",
          "number": 34,
          "text": "Mål om tillämpning av denna lag handlägges enligt lagen (1974:371) om rättegången i arbetstvister.",
          "references": [],
          "heading": "Rättegång"
        }
      ]
    }
  ],
  "transitional": [
    {
      "sfs": "1985:86",
      "text": "Denna lag träder i kraft den 1 juli 1985. Den nya bestämmelsen om semesterlönegrundande frånvaro i samband med havandeskapspenning tillämpas endast på frånvaro som har inträffat efter ikraftträdandet."
    },
    {
      "sfs": "1988:1468",
      "text": "1. Denna lag träder i kraft den 1 juli 1989.\n   2. Äldre bestämmelser skall gälla i fråga om ersättning enligt lagen (1956:293) om ersättning åt smittbärare. Lag (1989:339)."
    },
    {
      "sfs": "1990:102",
      "text": "1. Denna lag träder i kraft den 1 april 1990. Semesterledighet enligt den nya lagen utgår dock först under semesteråret den 1 april 1991 - den 31 mars 1992, om ej annat överenskommes.\n   2. Kollektivavtal eller annat avtal, som har träffats med utgångspunkt i äldre lag och innefattar sämre förmåner än som följer av den nya lagen, är i sådan del utan verkan."
    },
    {
      "sfs": "1992:1329",
      "text": "Denna lag träder i kraft den 1 april 1993. Såvitt avser semesterledighet tillämpas den nya lagen dock först under semesteråret den 1 april 1994--den 31 mars 1995."
    },
    {
      "sfs": "1993:334",
      "text": "Denna lag träder i kraft den 1 juni 1993. De nya bestämmelserna tillämpas vid beräkning av semesterlön för tid från och med den 1 april 1993.\nSemesterlön som intjänats före ikraftträdandet skall dock inte minskas."
    },
    {
      "sfs": "1994:1688",
      "text": "Denna lag träder i kraft den 1 januari 1995. Lagen skall dock inte tillämpas beträffande en övergång av ett företag, en verksamhet eller en del av en verksamhet som inträffat före ikraftträdandet."
    },
    {
      "sfs": "1999:1399",
      "text": "Denna lag träder i kraft den 1 juli 2001. Den äldre lydelsen gäller fortfarande i fråga om studiestöd som beviljats enligt den upphävda studiestödslagen (1973:349) eller enligt övergångsbestämmelserna till studiestödslagen (1999:1395)."
    },
    {
      "sfs": "2002:625",
      "text": "1. Denna lag träder i kraft den 1 januari 2003.\n   2. Äldre bestämmelser gäller fortfarande för särskilt utbildningsbidrag som avser tid före ikraftträdandet."
    },
    {
      "sfs": "2006:1529",
      "text": "1. Denna lag träder i kraft den 1 januari 2007.\n   2. Äldre bestämmelser gäller fortfarande i fråga om rekryteringsbidrag som har lämnats enligt den upphävda lagen (2002:624) om rekryteringsbidrag till vuxenstuderande."
    },
    {
      "sfs": "2009:1439",
      "text": "1. Denna lag träder i kraft den 1 april 2010.\n   2. De nya bestämmelserna i 17 § tillämpas första gången på frånvaroperioder som påbörjas efter ikraftträdandet. När det gäller den som vid lagens ikraftträdande på deltid är frånvarande från arbetet på grund av sjukdom eller arbetsskada, ska de nya bestämmelserna tillämpas redan från ikraftträdandet.\nLag (2011:129)."
    }
  ]
};
