// Skuldsaneringslag (2016:675)
// Generated by backend/build_laws_from_docx.py from the official DOCX (Regeringskansliet fulltext).
// Versions in force on 2026-10-07. Do not edit by hand - fix the parser or the source DOCX and regenerate.
// Last amended: t.o.m. SFS 2025:445

import { LegalText } from '../legalTexts';

export const skuldsaneringslagen: LegalText = {
  "id": "sfs-2016-675",
  "title": "Skuldsaneringslag (2016:675)",
  "sfsNumber": "2016:675",
  "department": "Justitiedepartementet L2",
  "issued": "2016-06-02",
  "lastAmended": "t.o.m. SFS 2025:445",
  "chaptered": false,
  "chapters": [
    {
      "id": "kap-1",
      "number": 1,
      "title": "Skuldsaneringslag (2016:675)",
      "sections": [
        {
          "id": "kap-1-§-1",
          "number": 1,
          "text": "Denna lag innehåller bestämmelser om skuldsanering. Skuldsanering innebär att en gäldenär helt eller delvis befrias från ansvar för betalningen av de skulder som omfattas av skuldsaneringen.\n\nI lagen (2016:676) om skuldsanering för företagare finns bestämmelser om en särskild form av skuldsanering för företagare och närstående till företagare.",
          "references": [],
          "heading": "Lagens innehåll"
        },
        {
          "id": "kap-1-§-2",
          "number": 2,
          "text": "Kronofogdemyndigheten ska lämna upplysningar om skuldsanering till svårt skuldsatta fysiska personer som är eller har varit föremål för verkställighet enligt utsökningsbalken.",
          "references": [],
          "heading": "Information och rådgivning till skuldsatta"
        },
        {
          "id": "kap-1-§-3",
          "number": 3,
          "text": "I 13 kap. 2 § socialtjänstlagen (2025:400) finns bestämmelser om att kommunen ska lämna budget- och skuldrådgivning till skuldsatta fysiska personer.\nLag (2025:445).",
          "references": [
            "13 kap. 2 §"
          ]
        },
        {
          "id": "kap-1-§-4",
          "number": 4,
          "text": "Kronofogdemyndigheten prövar ärenden om skuldsanering och ärenden om omprövning av ett beslut om skuldsanering.",
          "references": [],
          "heading": "Prövningsmyndighet"
        },
        {
          "id": "kap-1-§-5",
          "number": 5,
          "text": "Skuldsanering får beviljas en gäldenär som är en fysisk person om villkoren i 6-10 §§ är uppfyllda.",
          "references": [
            "6-10 §§"
          ],
          "heading": "Villkor för skuldsanering"
        },
        {
          "id": "kap-1-§-6",
          "number": 6,
          "text": "Skuldsanering får beviljas om gäldenären har sina huvudsakliga intressen i Sverige.",
          "references": []
        },
        {
          "id": "kap-1-§-7",
          "number": 7,
          "text": "Skuldsanering får beviljas om gäldenären är insolvent och så skuldsatt att han eller hon med hänsyn till samtliga omständigheter inte kan antas ha förmåga att betala sina skulder inom överskådlig tid. Lag (2022:998).",
          "references": []
        },
        {
          "id": "kap-1-§-8",
          "number": 8,
          "text": "Om gäldenären är en näringsidkare, får skuldsanering beviljas endast om de ekonomiska förhållandena i näringsverksamheten är enkla att utreda.\n\nEn gäldenär som har näringsförbud enligt lagen (2014:836) om näringsförbud får inte beviljas skuldsanering.",
          "references": []
        },
        {
          "id": "kap-1-§-9",
          "number": 9,
          "text": "Skuldsanering får beviljas om det är skäligt med hänsyn till gäldenärens personliga och ekonomiska förhållanden.\n\nVid skälighetsbedömningen ska särskilt beaktas omständigheterna vid skuldernas tillkomst, de ansträngningar gäldenären har gjort för att fullgöra sina förpliktelser och det sätt på vilket gäldenären har medverkat under handläggningen av ärendet om skuldsanering.",
          "references": []
        },
        {
          "id": "kap-1-§-10",
          "number": 10,
          "text": "Om gäldenären tidigare har beviljats skuldsanering, får skuldsanering beviljas endast om det finns särskilda skäl.",
          "references": []
        },
        {
          "id": "kap-1-§-11",
          "number": 11,
          "text": "En ansökan om skuldsanering ska vara skriftlig.\n\nAnsökan ska vara egenhändigt undertecknad av gäldenären. Om ansökan ges in på elektronisk väg, ska den vara undertecknad med en sådan avancerad elektronisk underskrift som avses i artikel 3 i Europaparlamentets och rådets förordning (EU) nr 910/2014 av den 23 juli 2014 om elektronisk identifiering och betrodda tjänster för elektroniska transaktioner på den inre marknaden och om upphävande av direktiv 1999/93/EG, i den ursprungliga lydelsen.",
          "references": [],
          "heading": "Ansökan om skuldsanering"
        },
        {
          "id": "kap-1-§-12",
          "number": 12,
          "text": "Ansökan ska innehålla uppgifter om\n   1. gäldenären enligt 5 § första stycket lagen (1996:242) om domstolsärenden och uppgifter som visar att gäldenären har sina huvudsakliga intressen i Sverige,\n   2. gäldenärens inkomster, tillgångar och utgifter,\n   3. de borgenärer som gäldenären känner till med angivande av varje borgenärs namn, adress och telefonnummer,\n   4. en uppskattning av skulden till varje borgenär,\n   5. omständigheterna vid skuldernas tillkomst och de ansträngningar gäldenären har gjort för att fullgöra sina förpliktelser, och\n   6. gäldenärens och dennes familjs personliga och ekonomiska förhållanden som i övrigt är av betydelse för prövningen av ärendet.\n\nUppgifterna ska lämnas av gäldenären på heder och samvete.",
          "references": [
            "5 §"
          ]
        },
        {
          "id": "kap-1-§-13",
          "number": 13,
          "text": "Om en ansökan är bristfällig, ska gäldenären föreläggas att avhjälpa bristen. Av föreläggandet ska det framgå att ansökan kan avvisas om föreläggandet inte följs. Föreläggandet behöver inte delges.\n\nEn ansökan om skuldsanering ska avvisas om den är så bristfällig att den inte kan läggas till grund för prövning i sak och gäldenären inte har följt ett föreläggande att avhjälpa bristen.",
          "references": [],
          "heading": "Komplettering och avvisning av ansökan"
        },
        {
          "id": "kap-1-§-14",
          "number": 14,
          "text": "En ansökan om skuldsanering ska avvisas om gäldenären är föremål för ett annat förfarande om skuldsanering.",
          "references": []
        },
        {
          "id": "kap-1-§-15",
          "number": 15,
          "text": "Kronofogdemyndigheten ska i den utsträckning det behövs 1. kontrollera i sina register att uppgifterna i ansökan är korrekta, och\n   2. inhämta upplysningar från andra myndigheter om gäldenärens personliga och ekonomiska förhållanden.\n\nEtt sammanträde enligt 22 § får hållas för att avgöra om skuldsanering ska inledas.",
          "references": [
            "22 §"
          ],
          "heading": "Inledande av skuldsanering"
        },
        {
          "id": "kap-1-§-16",
          "number": 16,
          "text": "Om det framgår av ansökan eller annan tillgänglig utredning att villkoren för skuldsanering inte är uppfyllda, ska ansökan avslås.\n\nAnsökan får också avslås om gäldenären inte infinner sig personligen vid ett sammanträde eller i övrigt inte medverkar under ärendets handläggning.",
          "references": []
        },
        {
          "id": "kap-1-§-17",
          "number": 17,
          "text": "Om ansökan inte avvisas eller avslås, ska Kronofogdemyndigheten snarast besluta att skuldsanering ska inledas (inledandebeslut).",
          "references": []
        },
        {
          "id": "kap-1-§-18",
          "number": 18,
          "text": "I inledandebeslutet ska det bestämmas vilket belopp som gäldenären ska betala för tiden till dess att frågan om skuldsanering slutligt har avgjorts eller något annat har bestämts. Det ska också bestämmas när och hur betalning ska ske.\n\nDet belopp som gäldenären ska betala ska bestämmas enligt 33 §.\n\nGäldenären ska betala till Kronofogdemyndigheten. Betalningarna ska genomföras trots att inledandebeslutet inte har fått laga kraft. För gäldenärens betalningar gäller i övrigt 38 § första stycket och 39 §.",
          "references": [
            "33 §",
            "38 §",
            "39 §"
          ]
        },
        {
          "id": "kap-1-§-19",
          "number": 19,
          "text": "När ett inledandebeslut har meddelats ska detta genast kungöras i Post- och Inrikes Tidningar. Om det finns särskilda skäl, får kungörelsen införas även i en eller flera ortstidningar.\n\nI kungörelsen ska varje borgenär som har en fordran mot gäldenären uppmanas att inom en månad från dagen för kungörelsen skriftligen\n   1. uppge sitt namn och person- eller organisationsnummer eller motsvarande identifieringsnummer,\n   2. anmäla sina fordringar mot gäldenären,\n   3. lämna närmare uppgifter om fordringarna och andra uppgifter av betydelse för prövningen av ärendet, och\n   4. ange till vilket konto som betalning ska ske.\n\nFristen i andra stycket får förlängas till två månader, om det finns särskilda skäl. Lag (2022:998).",
          "references": []
        },
        {
          "id": "kap-1-§-20",
          "number": 20,
          "text": "Efter inledandebeslutet ska Kronofogdemyndigheten se till att ärendet blir så utrett som dess beskaffenhet kräver.",
          "references": [],
          "heading": "Handläggningen efter inledandebeslut"
        },
        {
          "id": "kap-1-§-21",
          "number": 21,
          "text": "En underrättelse ska skickas till de borgenärer som är kända i ärendet senast en vecka efter att det enligt 19 § har kungjorts att ett inledandebeslut har meddelats.\n\nI underrättelsen ska borgenären upplysas om att ett inledandebeslut har meddelats och om borgenärens fordran i ärendet. Borgenären ska även uppmanas att inom den tidsfrist som anges i kungörelsen komma in med uppgifter enligt 19 § andra stycket.",
          "references": [
            "19 §"
          ]
        },
        {
          "id": "kap-1-§-22",
          "number": 22,
          "text": "Ett sammanträde ska hållas om det kan antas vara till fördel för utredningen. Vid sammanträdet ska gäldenären lämna de ytterligare upplysningar som behövs för prövningen av ärendet.\n\nGäldenären ska kallas att infinna sig personligen vid sammanträdet. Kallelsen ska sändas till gäldenären under den adress som han eller hon senast har uppgett i ärendet. Kallelsen behöver inte delges.\n\nI kallelsen ska gäldenären upplysas om syftet med sammanträdet och om att ansökan kan avslås om han eller hon inte infinner sig personligen.",
          "references": []
        },
        {
          "id": "kap-1-§-23",
          "number": 23,
          "text": "Till ett sammanträde enligt 22 § får även en borgenär eller någon annan som kan bidra till utredningen av ärendet kallas. Kallelsen behöver inte delges.",
          "references": [
            "22 §"
          ]
        },
        {
          "id": "kap-1-§-24",
          "number": 24,
          "text": "Om det efter inledandebeslutet framkommer att villkoren för skuldsanering inte är uppfyllda, ska ansökan avslås.\n\nAnsökan får också avslås om gäldenären inte infinner sig personligen vid ett sammanträde eller i övrigt inte medverkar under ärendets handläggning.",
          "references": []
        },
        {
          "id": "kap-1-§-25",
          "number": 25,
          "text": "När det finns tillräcklig utredning i ärendet, ska Kronofogdemyndigheten tillsammans med gäldenären upprätta ett förslag om skuldsanering som innehåller de uppgifter som anges i 29 §.",
          "references": [
            "29 §"
          ],
          "heading": "Beslut om skuldsanering"
        },
        {
          "id": "kap-1-§-26",
          "number": 26,
          "text": "Förslaget om skuldsanering ska sändas till samtliga kända borgenärer vars fordringar omfattas av förslaget med föreläggande för dem att yttra sig inom viss tid. Av föreläggandet ska det framgå att ett uteblivet yttrande inte hindrar ett beslut om skuldsanering. Föreläggandet ska delges borgenärerna.\n\nOm en fordran i ärendet inte omfattas av förslaget, ska borgenären underrättas om detta.",
          "references": []
        },
        {
          "id": "kap-1-§-27",
          "number": 27,
          "text": "Efter utgången av den tid som avses i 26 § ska Kronofogdemyndigheten besluta att skuldsanering ska beviljas, om villkoren för skuldsanering är uppfyllda.",
          "references": [
            "26 §"
          ]
        },
        {
          "id": "kap-1-§-28",
          "number": 28,
          "text": "När ett beslut om skuldsanering har meddelats ska detta genast kungöras i Post- och Inrikes Tidningar.",
          "references": []
        },
        {
          "id": "kap-1-§-29",
          "number": 29,
          "text": "I beslutet om skuldsanering ska det bestämmas\n   1. vilka fordringar som ska omfattas av skuldsaneringen (30-32 §§),\n   2. en betalningsplan som anger\n      a) det belopp som gäldenären ska betala (33 §),\n      b) planens längd och när den löper ut (34 §), och\n      c) när och hur gäldenären ska betala (38 §),\n   3. vilken avgift som Kronofogdemyndigheten ska ta ut (35 §),\n   4. vilket belopp som ska fördelas mellan borgenärerna (36 §) och hur stor procentandel av varje fordran som ska bli betald,\n   5. vad som ska gälla för fordringarna (37 §), och\n   6. när och hur borgenärerna ska få betalt (41 §).",
          "references": [
            "30-32 §§",
            "33 §",
            "34 §",
            "38 §",
            "35 §",
            "36 §",
            "37 §",
            "41 §"
          ],
          "heading": "Innehållet i en skuldsanering"
        },
        {
          "id": "kap-1-§-30",
          "number": 30,
          "text": "En skuldsanering omfattar, om inte annat föreskrivs i 31 § eller bestäms enligt 32 §, alla fordringar på pengar mot gäldenären som har uppkommit före den dag då inledandebeslutet meddelades.",
          "references": [
            "31 §",
            "32 §"
          ]
        },
        {
          "id": "kap-1-§-31",
          "number": 31,
          "text": "En skuldsanering omfattar inte\n   1. en fordran på familjerättsligt underhåll,\n   2. en fordran för vilken borgenären har panträtt eller annan förmånsrätt enligt 6 eller 7 § förmånsrättslagen (1970:979) eller retentionsrätt, till den del säkerheten räcker till för betalning av fordran,\n   3. en fordran för vilken borgenären, innan ett inledandebeslut har meddelats, har fått förmånsrätt enligt 8 § förmånsrättslagen, när det gäller egendom som har tagits i anspråk vid verkställigheten,\n   4. en fordran som inte är förfallen till betalning och som är beroende av att borgenären tillhandahåller en motprestation, eller\n   5. en fordran som är tvistig.\n\nEn fordran enligt första stycket 1 omfattas dock av skuldsaneringen om Försäkringskassan eller ett utländskt offentligt organ har inträtt i den underhållsberättigades rätt till underhållsbidrag.",
          "references": [
            "7 §",
            "8 §"
          ]
        },
        {
          "id": "kap-1-§-32",
          "number": 32,
          "text": "Om en fordran är beroende av villkor, inte är till beloppet fastställd eller inte är förfallen till betalning, får det bestämmas att den inte ska omfattas av skuldsaneringen.\n\nOm en fordran kan antas vara ogrundad, ska det bestämmas att den inte ska omfattas av skuldsaneringen.",
          "references": []
        },
        {
          "id": "kap-1-§-33",
          "number": 33,
          "text": "Det belopp som gäldenären ska betala enligt betalningsplanen ska bestämmas så att skuldsaneringen tar i anspråk gäldenärens samtliga tillgångar och inkomster efter avdrag för vad som ska förbehållas gäldenären för dennes och dennes familjs försörjning. Bestämmelserna i 7 kap. 4 och 5 §§ utsökningsbalken om förbehållsbelopp ska då vara vägledande.\n\nDet får bestämmas att förbehåll även ska göras för betalning av en fordran som inte omfattas av skuldsaneringen.",
          "references": [
            "7 kap. 4 och 5 §§"
          ]
        },
        {
          "id": "kap-1-§-34",
          "number": 34,
          "text": "Betalningsplanens längd ska vara fem år, om det inte finns beaktansvärda skäl att bestämma en kortare tid.\n\nBetalningsplanen börjar löpa från beslutet om skuldsanering.\n\nVid bestämmandet av tidpunkten för när betalningsplanen löper ut ska den tid som inledandebeslutet gällt räknas av från betalningsplanens längd, om det inte med hänsyn till gäldenärens agerande efter beslutet är motiverat att räkna av en kortare tid.",
          "references": []
        },
        {
          "id": "kap-1-§-35",
          "number": 35,
          "text": "Kronofogdemyndigheten ska ta ut en årlig avgift av gäldenären för myndighetens hantering av hans eller hennes betalningar.\n\nRegeringen får meddela föreskrifter om avgiftens storlek.",
          "references": []
        },
        {
          "id": "kap-1-§-36",
          "number": 36,
          "text": "Det belopp som ska fördelas mellan borgenärerna utgörs av de medel som gäldenären ska betala enligt inledandebeslutet och betalningsplanen med avdrag för den avgift som avses i 35 §.",
          "references": [
            "35 §"
          ]
        },
        {
          "id": "kap-1-§-37",
          "number": 37,
          "text": "Alla fordringar som omfattas av skuldsaneringen har lika rätt.\n\nTrots första stycket får en fordran\n   1. ges sämre rätt, om borgenären samtycker till det, eller\n   2. betalas före andra fordringar, om den efter fördelning enligt 36 § avser ett mindre belopp och det är skäligt med hänsyn till omfattningen av skulderna och övriga omständigheter.",
          "references": [
            "36 §"
          ]
        },
        {
          "id": "kap-1-§-38",
          "number": 38,
          "text": "Gäldenären ska betala en gång i månaden, med undantag för juni och december som är betalningsfria månader.\n\nGäldenären ska betala till Kronofogdemyndigheten. Om det finns särskilda skäl, får det bestämmas att gäldenären i stället ska betala direkt till borgenärerna.\n\nBetalningarna ska genomföras trots att beslutet om skuldsanering inte har fått laga kraft.",
          "references": [],
          "heading": "Gäldenärens betalningar"
        },
        {
          "id": "kap-1-§-39",
          "number": 39,
          "text": "Gäldenären förlorar rådigheten över medel som han eller hon har betalat in till Kronofogdemyndigheten. Myndigheten ska genast placera de inbetalda medlen på ett räntebärande konto.",
          "references": []
        },
        {
          "id": "kap-1-§-40",
          "number": 40,
          "text": "Inbetalda medel tillfaller de borgenärer vars fordringar omfattas av skuldsaneringen, när beslutet om skuldsanering har fått laga kraft och den avgift som avses i 35 § har räknats av.",
          "references": [
            "35 §"
          ]
        },
        {
          "id": "kap-1-§-41",
          "number": 41,
          "text": "Inbetalda medel som tillhör borgenärerna jämte ränta ska Kronofogdemyndigheten betala ut till borgenärerna en gång om året.\n\nUtbetalning till en borgenär ska göras till det konto som angetts av borgenären. Om det finns särskilda skäl, får utbetalning göras på annat sätt.\n\nOm utbetalning till en borgenär inte görs, ska en underrättelse skickas till borgenären. Lag (2022:998).",
          "references": []
        },
        {
          "id": "kap-1-§-41a",
          "number": 41,
          "text": "En borgenär förlorar sin rätt till inbetalda medel enligt 40 § om borgenären inte inom tre månader från dagen för den sista utbetalningen till borgenärerna enligt beslutet om skuldsanering lämnar sådana uppgifter till Kronofogdemyndigheten att medlen kan betalas ut till borgenären enligt 41 § andra stycket.\n\nDe medel som en borgenär har förlorat sin rätt till ska fördelas mellan övriga borgenärer och i andra hand betalas tillbaka till gäldenären. Om utbetalning eller återbetalning inte är möjlig, tillfaller medlen staten. Lag (2022:998).",
          "references": [
            "40 §",
            "41 §"
          ],
          "suffix": "a"
        },
        {
          "id": "kap-1-§-42",
          "number": 42,
          "text": "Efter inledandebeslutet får utmätning för fordringar som uppkommit dessförinnan inte ske innan frågan om skuldsanering är avgjord genom ett beslut som har fått laga kraft. Om utmätning ändå sker, är åtgärden utan verkan.\n\nFörsta stycket gäller inte fordringar som enligt 31 § inte omfattas av skuldsaneringen. Det gäller inte heller om, efter överklagande, rätten på begäran av en borgenär bestämmer att utmätning får ske.\n\nDenna paragraf tillämpas även i fråga om ett beslut om betalningssäkring och verkställighet av ett sådant beslut.",
          "references": [
            "31 §"
          ],
          "heading": "Exekutiva åtgärder"
        },
        {
          "id": "kap-1-§-43",
          "number": 43,
          "text": "Inbetalda medel som fortfarande tillhör gäldenären får inte utmätas eller tas i anspråk för verkställighet av ett beslut om betalningssäkring.",
          "references": []
        },
        {
          "id": "kap-1-§-44",
          "number": 44,
          "text": "Ett beslut om skuldsanering får verkställas när det har fått laga kraft. Verkställighet får inte avse annat än vad som redan skulle ha betalats ut till borgenären enligt beslutet om skuldsanering.",
          "references": []
        },
        {
          "id": "kap-1-§-45",
          "number": 45,
          "text": "Kronofogdemyndighetens beslut får överklagas. Ett beslut som inte innebär att ärendet avgörs får överklagas endast i samband med överklagande av ett beslut som innebär att ärendet avgörs. Inledandebeslutet och beslut om ändring av inledandebeslutet får dock överklagas särskilt.\n\nKronofogdemyndighetens beslut överklagas till tingsrätten i den ort där gäldenären är bosatt. Om gäldenären inte är bosatt i Sverige, överklagas beslutet till Stockholms tingsrätt. Ett överklagande ska ges in till Kronofogdemyndigheten inom tre veckor från dagen för beslutet.\n\nVid ett överklagande gäller lagen (1996:242) om domstolsärenden, om inte annat följer av denna lag. Kronofogdemyndigheten ska inte vara part i domstolen.",
          "references": [],
          "heading": "Överklagande"
        },
        {
          "id": "kap-1-§-46",
          "number": 46,
          "text": "Om en domstol bifaller ett överklagande av gäldenären, ska den återförvisa ärendet till Kronofogdemyndigheten. Om Kronofogdemyndigheten har avslagit gäldenärens ansökan med tillämpning av 24 § och tillräcklig utredning finns, får domstolen dock besluta om skuldsanering.\n\nEtt beslut att återförvisa ett ärende till Kronofogdemyndigheten får inte överklagas.",
          "references": [
            "24 §"
          ]
        },
        {
          "id": "kap-1-§-47",
          "number": 47,
          "text": "Genom en skuldsanering befrias gäldenären från ansvar för betalningen av de skulder som omfattas av skuldsaneringen i den utsträckning som dessa sätts ned. Genom skuldsaneringen befrias gäldenären även från ansvar för betalningen av skulder som inte är kända i ärendet, om det inte är en sådan skuld som avses i 31 §.\n\nSkuldsaneringen medför att rätten till ränta eller dröjsmålsavgift på en fordran som omfattas av skuldsaneringen faller bort för tiden efter den dag då inledandebeslutet meddelades.\n\nSkuldsaneringen inverkar inte på den rätt en borgenär har mot en borgensman eller någon annan som förutom gäldenären svarar för skulden.",
          "references": [
            "31 §"
          ],
          "heading": "Verkan av en skuldsanering"
        },
        {
          "id": "kap-1-§-48",
          "number": 48,
          "text": "På ansökan av en borgenär vars fordran omfattas av skuldsaneringen får beslutet om skuldsanering upphävas eller, i fall som avses i 6 och 7, ändras beträffande det som har bestämts i en fråga som avses i 29 § 2-6, om\n   1. gäldenären har gjort sig skyldig till oredlighet mot borgenärer,\n   2. gäldenären har gjort sig skyldig till uppsåtligt försvårande av konkurs eller exekutiv förrättning,\n   3. gäldenären i hemlighet har gynnat någon borgenär för att inverka på skuldsaneringsfrågans avgörande,\n   4. gäldenären i sin ansökan om skuldsanering eller annars under ärendets handläggning medvetet har lämnat oriktiga uppgifter till men för borgenären,\n   5. gäldenären har lämnat oriktiga uppgifter till ledning för en myndighets beslut i fråga om skatt eller avgift som omfattas av skuldsaneringen eller inte har lämnat uppgifter trots att han eller hon är uppgiftsskyldig och detta har medfört att ett beslut blivit felaktigt eller inte fattats,\n   6. gäldenären inte följer betalningsplanen och avvikelsen inte är ringa, eller\n   7. gäldenärens ekonomiska förhållanden väsentligen har förbättrats efter beslutet om skuldsanering och detta beror på omständigheter som inte kunnat förutses vid beslutet.\n\nI fall som avses i första stycket 7 ska ansökan göras inom fem år från dagen för inledandebeslutet eller, om en betalningsplan löper ut senare, senast den dag då planen löper ut.",
          "references": [
            "29 §"
          ],
          "heading": "Omprövning av ett beslut om skuldsanering"
        },
        {
          "id": "kap-1-§-49",
          "number": 49,
          "text": "På ansökan av gäldenären får beslutet om skuldsanering ändras beträffande det som har bestämts i en fråga som avses i 29 § 2-6, om\n   1. gäldenärens ekonomiska förhållanden väsentligen har förändrats efter beslutet om skuldsanering och detta beror på omständigheter som inte kunnat förutses vid beslutet, eller\n   2. det finns synnerliga skäl.",
          "references": [
            "29 §"
          ]
        },
        {
          "id": "kap-1-§-50",
          "number": 50,
          "text": "Om ett beslut om skuldsanering upphävs, blir en borgen eller annan säkerhet som tredje man har ställt för betalning av ett belopp som avses i 29 § 4 ogiltig. Detta gäller dock inte om tredje mannen kände till eller borde ha känt till de omständigheter som anges i 48 § första stycket 1-3 eller medverkade till att gäldenären har åsidosatt sina förpliktelser enligt 48 § första stycket 4.",
          "references": [
            "29 §",
            "48 §"
          ]
        },
        {
          "id": "kap-1-§-51",
          "number": 51,
          "text": "Vid en ändring av ett beslut om skuldsanering får betalningsplanens längd bestämmas till som längst sju år.",
          "references": []
        },
        {
          "id": "kap-1-§-52",
          "number": 52,
          "text": "En ansökan om omprövning av ett beslut om skuldsanering ska vara skriftlig. Ansökan ska innehålla uppgifter om\n   1. det beslut som avses,\n   2. det som yrkas, och\n   3. de omständigheter som åberopas till stöd för ansökan.\n\nOm en ansökan är bristfällig tillämpas 13 §.",
          "references": [
            "13 §"
          ]
        },
        {
          "id": "kap-1-§-53",
          "number": 53,
          "text": "Bestämmelserna i 20, 22 och 23 §§ gäller vid handläggningen av ett ärende om omprövning av ett beslut om skuldsanering.",
          "references": [
            "20, 22 och 23 §§"
          ]
        },
        {
          "id": "kap-1-§-54",
          "number": 54,
          "text": "Om gäldenären försätts i konkurs, förfaller ansökan om skuldsanering.\n\nOm en ansökan om planförhandling under företagsrekonstruktion tas upp sedan gäldenären har ansökt om skuldsanering, ska skuldsaneringsärendet förklaras vilande. Om en rekonstruktionsplan fastställs, förfaller ansökan om skuldsanering.\n\nOm gäldenären avlider, förfaller ansökan om skuldsanering.\nLag (2022:998).",
          "references": [],
          "heading": "Övriga bestämmelser"
        },
        {
          "id": "kap-1-§-55",
          "number": 55,
          "text": "Om gäldenären återkallar en ansökan om skuldsanering, ska ärendet avskrivas från vidare handläggning. Detsamma gäller om ansökan förfaller enligt 54 §.",
          "references": [
            "54 §"
          ]
        },
        {
          "id": "kap-1-§-56",
          "number": 56,
          "text": "Om en ansökan om skuldsanering avslås eller avvisas eller ärendet avskrivs från vidare handläggning sedan ett inledandebeslut har meddelats, ska samtliga kända borgenärer underrättas.\n\nVid beslut om avslag, avvisning eller avskrivning ska medel som gäldenären har betalat in till Kronofogdemyndigheten återbetalas till honom eller henne när beslutet har fått laga kraft. Om en pågående utmätning har avbrutits genom inledandebeslutet, ska i stället inbetalda medel fördelas mellan de fordringar för vilka utmätningen pågick.",
          "references": []
        },
        {
          "id": "kap-1-§-57",
          "number": 57,
          "text": "Om det har bestämts att en fordran enligt 32 § första stycket inte ska omfattas av skuldsaneringen, får borgenären trots föreskrifter i annan författning bevilja anstånd med betalningen under den tid betalningsplanen löper.",
          "references": [
            "32 §"
          ]
        },
        {
          "id": "kap-1-§-58",
          "number": 58,
          "text": "En överenskommelse som innebär att gäldenären eller tredje man tillförsäkrar någon borgenär, vars fordran omfattas av skuldsaneringen, bättre villkor än enligt skuldsaneringen är ogiltig.",
          "references": []
        },
        {
          "id": "kap-1-§-59",
          "number": 59,
          "text": "Socialnämnder och andra myndigheter ska till Kronofogdemyndigheten eller en domstol som handlägger ett ärende om skuldsanering på begäran lämna uppgifter om gäldenärens personliga och ekonomiska förhållanden som är av betydelse för prövningen av ärendet. Sådana uppgifter ska också lämnas av myndigheter som anmäler fordringar enligt 19 eller 21 §.",
          "references": [
            "21 §"
          ]
        },
        {
          "id": "kap-1-§-60",
          "number": 60,
          "text": "I lagen (2017:473) med kompletterande bestämmelser till 2015 års insolvensförordning finns bestämmelser om registrering av skuldsaneringar i ett insolvensregister.\nLag (2019:253).",
          "references": []
        }
      ]
    }
  ],
  "transitional": [
    {
      "sfs": "2016:675",
      "text": "1. Denna lag träder i kraft den 1 november 2016.\n   2. Genom lagen upphävs skuldsaneringslagen (2006:548).\n   3. Bestämmelserna i 18 § och 34 § tredje stycket tillämpas inte för ett ärende där ett beslut att inleda skuldsanering enligt skuldsaneringslagen (2006:548) har meddelats före ikraftträdandet.\n   4. Äldre bestämmelser gäller för beslut om skuldsanering som har fått laga kraft före ikraftträdandet, om inte annat framgår av punkten 5.\n   5. Om ett beslut om skuldsanering som avses i punkten 4 ändras efter omprövning, får det på gäldenärens begäran bestämmas att hans eller hennes betalningar fortsättningsvis ska ske till Kronofogdemyndigheten i enlighet med 38 § andra stycket. I sådant fall gäller för beslutet även 29, 33 och 35-37 §§, 38 § tredje stycket och 39-53 §§. Vilka fordringar som omfattas av skuldsaneringen får inte ändras."
    },
    {
      "sfs": "2022:998",
      "text": "1. Denna lag träder i kraft den 1 augusti 2022.\n   2. Bestämmelsen i 19 § i den nya lydelsen gäller inte för ärenden där ett beslut att inleda skuldsanering har meddelats före ikraftträdandet.\n   3. Den nya 41 a § gäller även i fråga om ärenden där betalningsplanen löpt ut före ikraftträdandet. För sådana ärenden tillämpas paragrafen dock från och med den 1 november 2022.\n   4. Bestämmelsen i 54 § i den äldre lydelsen gäller fortfarande för det fall beslut om förhandling om offentligt ackord meddelas eller ett ackord fastställs enligt den upphävda lagen (1996:764) om företagsrekonstruktion efter att gäldenären ansökt om skuldsanering."
    }
  ]
};
